### ISSUE TITLE
Feature Request: Add tracing of native methods

### ISSUE THREAD

**Issue by eGit** [btraceio/btrace#115]
Add tracing of native methods to BTrace.

**Comment by jbachorik** [comment]
eGit, this feature seems to be breaking class retransformation when trying to trace non-static native methods. Do you think it would be interesting to be able to trace at least static native methods?

Otherwise I will have to remove this feature.

**Comment by jbachorik** [comment]
Reopening because of #140

**Comment by eGit** [comment]
I just wanted to test the native method tracing for the first time but now it is gone again?

**Comment by jbachorik** [comment]
It is not possible to achieve this functionality with the current
limitations of the JVM class retransformation. One may need to introduce
new public non-native methods as wrappers for the original public native
methods and this is simply not possible. So I had to take it out again.
Maybe once, when JVM gets an improved class retransformation engine.
