### ISSUE TITLE
Identifying method scope with BTrace

### ISSUE THREAD

**Issue by dictin** [btraceio/btrace#202]
Hello, 

I'm currently trying to trace all of the different calls made inside of a package and I would like each of these call to be recorded in their Java signature, including their scope. 

I have used `@ProbeMethodName(fqn=true)` to get the VM method signature but it doesn't seem to include the scope of the method. Is there a way to identify the scope when tracing a method call with Btrace?

For example, if the probed method is:

`public int Foo(String param1, String param2){...}`

I would like the trace log to tell me that the Method Foo was public.

Would that be possible?

**Comment by jbachorik** [comment]
This would be possible. The `@ProbeMethodName` annotation would have to be extended with a new boolean attribute eg. `showAccess` to turn this on.
