### ISSUE TITLE
question:what does the 'type' property of @OnMethod annotation mean?

### ISSUE THREAD

**Issue by ymmihw** [btraceio/btrace#230]
```
    @OnMethod(
        clazz="java.io.FileInputStream",
        method="<init>",
        type="void (java.io.File)", // here <=============================
        location=@Location(Kind.RETURN)
    )
    public static void onNewFileInputStreamReturn() {
        if (name != null) {
            println("opened for read " + name);
            name = null;
        }
    }
```

**Comment by jbachorik** [comment]
It allows you to specify the signature of the methods you want to intercept, without the necessity to spell the parameters in the probe handler method. 
Generally, if you are not going to use the method parameters values it is better not to capture them in the probe handler - it will save some stack space as well CPU cycles.

Also, see the [javadoc](https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/annotations/OnMethod.java#L65)

**Comment by ymmihw** [comment]
when the method intercepted is a constructor, does btrace ignores the return type?

i modified the sample 'FileTracker.java' as follow, it still works.
```
    @OnMethod(
        clazz="java.io.FileInputStream",
        method="<init>",
        type="int (java.io.File)", // here <=============================
        location=@Location(Kind.RETURN)
    )
    public static void onNewFileInputStreamReturn() {
        if (name != null) {
            println("opened for read " + name);
            name = null;
        }
    }
```
