### ISSUE TITLE
Creating a concurrent Map

### ISSUE THREAD

**Issue by mjpt777** [btraceio/btrace#232]
Is it possible to create a new concurrent Map rather than a plain HashMap so it is thread safe? The examples show the use of AtomicIntegers in maps but the map is a HashMap which is not thread safe.

**Comment by jbachorik** [comment]
Currently, it is not implemented in `BTraceUtils`. As a workaround you can create your own [extension](http://btraceio.github.io/btrace/2014/11/services-final) to provide some extra functionality not available in the core classes.

**Comment by mjpt777** [comment]
On reflection is this not a serious bug? A HashMap will be corrupted by concurrent threads.

**Comment by jbachorik** [comment]
Not really - the instance you get by calling `BTraceUtils.newHashMap()' is implicitly synchronized (equivalent to `Collections.synchronizedMap()`). The map will not be corrupted but it doesn't prevent racy data.

**Comment by mjpt777** [comment]
Thanks. I did not realise BTraceMap was synchronized. It would help if their was some JavaDoc on BTraceUtils to explain this :)
