### ISSUE TITLE
BTrace agent connection not properly shut down when leaving the dynamically attached session

### ISSUE THREAD

**Issue by jbachorik** [btraceio/btrace#239]
As described at [StackOverflow](http://stackoverflow.com/questions/39106323/how-to-shutdown-btrace)

**Comment by Kshitiz-Sharma** [comment]
Not sure if this is a bug. Running in verbose mode didn't reveal anything. 

I'm stopping the client by doing Ctrl+C. Do we have any JVM shutdown hooks to trigger exit in this case? 

DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling ContextCapturedOnExceptionExampleTracer.java
DEBUG: compiled ContextCapturedOnExceptionExampleTracer.java
DEBUG: attaching to 4984
DEBUG: checking port availability: 2020
DEBUG: attached to 4984
DEBUG: loading C:\Development\Software\btrace-1.3.8\build\btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=C:\Program Files\Java\jdk1.8.0_92\jre/../lib/tools.jar,probeDescPath=.
DEBUG: loaded C:\Development\Software\btrace-1.3.8\build\btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command
DEBUG: entering into command loop
DEBUG: received com.sun.btrace.comm.RenameCommand@130f889
DEBUG: received com.sun.btrace.comm.OkayCommand@1188e820
DEBUG: received com.sun.btrace.comm.RetransformationStartNotification@2f490758
DEBUG: received com.sun.btrace.comm.OkayCommand@101df177
DEBUG: received com.sun.btrace.comm.MessageCommand@33b37288
DEBUG: received com.sun.btrace.comm.MessageCommand@77a57272
DEBUG: received com.sun.btrace.comm.MessageCommand@4e4aea35
DEBUG: received com.sun.btrace.comm.MessageCommand@679b62af
DEBUG: received com.sun.btrace.comm.MessageCommand@58fdd99
