### ISSUE TITLE
How to configure for support sub thread?

### ISSUE THREAD

**Issue by liukeyou** [btraceio/btrace#243]
I'm attach the  process(process_aaa) with somes sub threads(sub-thread1/sub-thread2...sub-threadN)  for traceing a function(function_yyy) call, but the print info only shows the process_aaa call.
    process_aaa -->  call function_yyy(111)
          sub-thread1  -->  call function_yyy(222)
          sub-thread1  -->  call function_yyy(222)
          ....
          sub-threadN  -->  call function_yyy(222)
   only prints 111

How to configure for support sub thread?

**Comment by jbachorik** [comment]
My first guess is that the method you are trying to trace the calls from is still running, eg. on stack, and therefore still executing the uninstrumented code. I might be able to tell more if you could share the script you are using.

**Comment by liukeyou** [comment]
app bugs
