### ISSUE TITLE
Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by alexKeleon** [btraceio/btrace#247]
**kernel version is**
$ uname -a
Linux bonus-platform-service08.nh 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**my jdk version is**
$ java -version
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

**pid of  jvm process is** 
$ ps -ef | grep java
nobody   20151     1 99 12:09 ?        04:58:17 /usr/local/jdk/bin/java -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -javaagent..........

**then run the script**
$ sudo sh -x  ./btrace 20151  ../samples/Test.java
+ '[' -z '' -o '!' -d '' ']'
+ PRG=./btrace
++ basename ./btrace
+ progname=btrace
++ dirname ./btrace
+ BTRACE_HOME=./..
++ cd ./..
++ pwd
+ BTRACE_HOME=/data/btrace
+ MYJAVA_HOME=/usr/local/jdk
+ '[' -f /data/btrace/build/btrace-client.jar ']'
+ '[' /usr/local/jdk '!=' '' ']'
+ case "`uname`" in
++ uname
+ TOOLS_JAR=/usr/local/jdk/lib/tools.jar
+ /usr/local/jdk/bin/java -Dcom.sun.btrace.probeDescPath=. -Dcom.sun.btrace.dumpClasses=false -Dcom.sun.btrace.debug=false -Dcom.sun.btrace.unsafe=false -cp /data/btrace/build/btrace-client.jar:/usr/local/jdk/lib/tools.jar:/usr/share/lib/java/dtrace.jar com.sun.btrace.client.Main 20151 ../samples/Test.java

**the reuslt is** 
Unable to open socket file: target process not responding or HotSpot VM not loaded

**Comment by alexKeleon** [comment]
the btrace's version is release-1.2.4

**Comment by jbachorik** [comment]
1. The Java version is pretty pre-historic. Is there a chance you could use
JDK 7 or at least some of the latest update release of JDK 6?
2. The tomcat process seems to be started with a java agent - what is that
agent?
3. You are running btrace as root but the target process seems to be owned
by 'nobody' - this is not guaranteed to work because of the limitations of
the Attach API (you can connect only to the same-user processes)

**Comment by alexKeleon** [comment]
> 2. The tomcat process seems to be started with a java agent - what is that
> agent?

java agent is 
-javaagent:/usr/local/tomcat/bin/../lib/cookie-java-agent-0.1.jar -javaagent:/usr/local/tomcat/bin/../lib/byteman-2.1.2.jar=script:/usr/local/tomcat/bin/../lib/cookie.btm
