### ISSUE TITLE
[BTRACE-78] Ability to find values of local variables when reaching specific line number using @Location

### ISSUE THREAD

**Issue by jbachorik** [btraceio/btrace#25]
<b><i>[reporter="jerusalemer", created="Thu, 13 Oct 2011 18:18:22 +0200"]</i></b>

<p>The existing ability to go a specific line in method can become much more usable if there is an ability to find out the values of local variables at that specific line.</p>

**Comment by whitelilis** [comment]
I'm looking for this feature, then see this issue. I wish it will come soon.

**Comment by lawnight** [comment]
this's a great feature.hope come soon.

**Comment by kylemeow** [comment]
+1 for this feature : )
