### ISSUE TITLE
fail to use btrace with 1.7.0_80 on mac

### ISSUE THREAD

**Issue by afredlyj** [btraceio/btrace#251]
I download `btrace-bin-1.3.8.3.zip` and want to run a test on Mac , but when startup btrace script, the target jvm output below , and no output from btrace script :
```java
objc[8715]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
```
Then I run my code on windows7, it works fine.

So what's wrong with btrace or something else with jdk?

**Comment by jbachorik** [comment]
This looks like the functionality previously available only via tools.jar is now a part of JRE?

I do not own any MacOS machine so it would be nice if someone running a Mac could play with the 'bin/btrace' script to see what happens when the reference to tools.jar is removed (line `${JAVA_HOME}/bin/java -cp ${BTRACE_HOME}/build/btrace-client.jar:${TOOLS_JAR}:/usr/share/lib/java/dtrace.jar com.sun.btrace.client.Main $*`)

**Comment by tmohme** [comment]
I'm able to run btrace with Java 1.8.0_65 on my Mac (10.11.6) without any problems - and without this message.
Nevertheless I also have seen the mentioned message some time ago when I might have used Java 1.7.0_xx. 
Then it was really tenacious but besides this it was harmless.
Google shows many entries for this message, there's even an [OpenJDK Bug](https://bugs.openjdk.java.net/browse/JDK-8022291).

I don't think the message has anything to do with your problems using btrace.

**Comment by tmohme** [comment]
. . . have to correct myself: In my test some moments before I didn't get the message on the terminal from where I started btrace.
Instead I got the message on the terminal from where I started the traced application (which I missed in my last post).
Besides from the message unexpectedly showing up, I had no problems. Neither with the application, nor with btrace.

**Comment by afredlyj** [comment]
After I remove the line `${JAVA_HOME}/bin/java -cp ${BTRACE_HOME}/build/btrace-client.jar:${TOOLS_JAR}:/usr/share/lib/java/dtrace.jar com.sun.btrace.client.Main $*`,
the command `btrace` just quit without any log.

**Comment by afredlyj** [comment]
Sorry, my mistake.
I refactored my project last time, and forgot changing package name in btrace script.
