### ISSUE TITLE
How to print the local variable

### ISSUE THREAD

**Issue by discalced** [btraceio/btrace#255]
Is there any example shows how to print method local variable when the location is **Kind.CATCH**?I have a server program that always throw exceptions. I set the location to **Kind.CATCH** and pass the **@self** argument, the method can print something when exception happened. but when i add the other argument to the method, the method print nothing.  i tried the AnyType , too. still not work.

is there any samples that i can follow? thanks a lot.

English is not my native language, hope you can understand me.

**Comment by jbachorik** [comment]
Which local variable you need to access for for the location `Kind.CATCH`? Normally, the caught exception instance will be passed as `@Self`. Other than that there is no support for inspecting the local variables in BTrace yet.

**Comment by jbachorik** [comment]
Was my last answer helpful?

**Comment by discalced** [comment]
sorry for the late reply. now i'm clear about the question, thanks a lot!

**Comment by jbachorik** [comment]
Ok, thanks for the reply.
