### ISSUE TITLE
Why i cant use "btrace"?

### ISSUE THREAD

**Issue by carryxyh** [btraceio/btrace#257]
I set the BTRACE_HOME and when i use 'btrace ....' , it tell me "Please set BTRACE_HOME before running this script"

I have been set the BTRACE_HOME:
echo $BTRACE_HOME
/Users/...../btrace

Are u kidding me?

**Comment by jbachorik** [comment]
I try not to.

Can you provide more details? `/Users/...../btrace` doesn't look like a valid path for a starter.

Which version are you using. Can you verify that the distribution archive was properly unarchived (eg. there are 3 jar files in __<btrace_home>/build/__ directory?

**Comment by carryxyh** [comment]
The version is 1.3.8. My os is MAC OS 10.10.5.
The "/Users/...../btrace" is the btrace directory in my computer , and i hide something personal . I carry out "echo $BTRACE_HOME" in my terminal, it prints "/Users/...../btrace".Then I carry out "echo $PATH" in my terminal ,it prints "$PATH:/Users/...../btrace/bin". Thats it.
I download the btrace from git(the version is 1.3.8 , the latest)  and i never deal it.
I just run ./btrace in the bin directory.

**Comment by carryxyh** [comment]
<img width="411" alt="826dff6a-b975-45b6-8ab7-b4ad2889a9b2" src="https://cloud.githubusercontent.com/assets/12047600/21266235/208f915a-c3e0-11e6-90fd-160bf6fe0ab5.png">

**Comment by carryxyh** [comment]
Why?!

**Comment by jbachorik** [comment]
I don't know. For almost everybody it just works. I've just tried to download the archive from github (actually, the version is 1.3.8.3), uncompress it and run. And it works out of the box - no need to set BTRACE_HOME, it is automatically inferred.

You either have corrupted installation or permission problems. 

I would recommend re-downloading the archive, uncompressing it to eg. `/tmp/btrace` and trying from there  to see whether the problem is reproducible.

**Comment by carryxyh** [comment]
I dont think it caused by permission. Because I run it as root.
I try to re-downloading the archive , and I uncompressing it to /tmp/btrace.
Before running the shell -> btrace .  I do noting with the archive.
Disappointed，it donsnt work too.

I alter the shell 'btrace' : 


---------------------------------------------------
#! /bin/sh

if [ -z "$BTRACE_HOME" -o ! -d "$BTRACE_HOME" ] ; then
  # resolve links - $0 could be a link to btrace's home
  PRG="$0"
  progname=`basename "$0"`
  BTRACE_HOME=`dirname "$PRG"`/..
  BTRACE_HOME=`cd "$BTRACE_HOME" && pwd`
fi

#if [ -f "${BTRACE_HOME}/build/btrace-client.jar" ] ; then
    if [ "${JAVA_HOME}" != "" ]; then
         TOOLS_JAR="${JAVA_HOME}/lib/tools.jar"
         if [ ! -f ${TOOLS_JAR} ] ; then
           case "`uname`" in
             Darwin*)
               # In older JDK versions for Mac OS X, tools.jar is classes.jar 
               # and is kept in a different location. Check if we can locate
               # classes.jar based on ${JAVA_VERSION}
               TOOLS_JAR="/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Classes/classes.jar"

               # if we can't find, try relative path from ${JAVA_HOME}. Usually,
               # /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
               # is JAVA_HOME. (or whatever version beyond 1.6.0!)
               if [ ! -f ${TOOLS_JAR} ] ; then
                 TOOLS_JAR="${JAVA_HOME}/../Classes/classes.jar"
               fi

               # If we still can't find, tell the user to set JAVA_VERSION.
               # This way, we can avoid zip file errors from the agent side
               # and "connection refused" message from client.
               if [ ! -f ${TOOLS_JAR} ] ; then
                 echo "Please set JAVA_VERSION to the target java version"
                 exit 1
               fi
               ;;
           esac
         fi
       ${JAVA_HOME}/bin/java -cp ${BTRACE_HOME}/build/btrace-client.jar:${TOOLS_JAR}:/usr/share/lib/java/dtrace.jar com.sun.btrace.client.Main $*
    else
       echo "Please set JAVA_HOME before running this script"
       exit 1
    fi
#else
#    echo "Please set BTRACE_HOME before running this script"
#    exit 1
#fi
---------------------------------------------------

And then i cd /tmp/btrace and run 'gradle build'.
Then i cd the bin and  run  ./btrace -h. It works  and  print : 

---------------------------------------------------
Usage: btrace <options> <pid> <btrace source or .class file> <btrace arguments>
where possible options include:
  --version             Show the version
  -v                    Run in verbose mode
  -o <file>             The path to store the probe output (will disable showing the output in console)
-u                    Run in unsafe mode
  -d <path>             Dump the instrumented classes to the specified path
  -pd <path>            The search path for the probe XML descriptors
  -classpath <path>     Specify where to find user class files and annotation processors
  -cp <path>            Specify where to find user class files and annotation processors
  -I <path>             Specify where to find include files
  -p <port>             Specify port to which the btrace agent listens for clients
  -statsd <host[:port]> Specify the statsd server, if any
---------------------------------------------------

I think  there have something wrong with the shell 'btrace', can  u  fix  it  after  this  version?
Thanks.

**Comment by carryxyh** [comment]
I know the reason.
I download the archive but I still not to build it  , so  when I run ./btrace  it  calls  "please set BTRACE_HOME". The error message  is  not suitable!
I have already set the BTRACE_HOME but I dont have the  $BTRACE_HOME/build/btrace-client.jar and it should  prompt me I dont have the btrace-client.jar but not prompt me I dont set the BTRACE_HOME.

Can u fix it after this version ?

**Comment by jbachorik** [comment]
You need to either
- download binary archive ([btrace-bin.zip](https://github.com/btraceio/btrace/releases/download/v1.3.8.3-1/btrace-bin-1.3.8.3.zip), [btrace-bin.tgz](https://github.com/btraceio/btrace/releases/download/v1.3.8.3-1/btrace-bin-1.3.8.3.tgz)) and use it right away
- download source archive ([source.zip](https://github.com/btraceio/btrace/archive/v1.3.8.3-1.zip), [source.tgz](https://github.com/btraceio/btrace/archive/v1.3.8.3-1.tgz)) and build it before using

If you have source archive and don't build it you are missing crucial jars and the script can not validate that the location from where you are trying to run BTrace is a valid BTRACE_HOME - hence the error message.
