### ISSUE TITLE
synchronized on method synExit never trigger!

### ISSUE THREAD

**Issue by yanfeipeng** [btraceio/btrace#264]
Hi @jbachorik 
version 1.3.8.3
my test class:

`import java.io.IOException;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class BtraceSynCheckTest {

	public static synchronized void test() {
		System.out.println("call test");
	}
	
	public static void test2() {
		synchronized (BtraceSynCheckTest.class) {
			System.out.println("call test2 block");
		}
	}

	public static void main(String[] args) {

		try {
			Thread.sleep(30000);
		} catch (InterruptedException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	
		new NewClz().myTest();
		
		test2();
				
	        test();

	}
	
	static class NewClz {
		
		public synchronized void myTest() {
			System.out.println("call myTest block");
		}
	}

}`

btrace script:
`@OnMethod(
			 clazz="/com\\.baitian\\.test\\.test\\..*/",
			 method="/.*/",
			 location=@Location(Kind.SYNC_EXIT)
	 )
	public static void onSyncExit() {
		println("before synchronized exit");
	}`

but the test()  and myTest() after called exit, never println the infos("before synchronized exit")!
Is it someting wrong with the com.sun.btrace.runtime.instr.SynchronizedInstrumentor.java

**Comment by yanfeipeng** [comment]
I fix this problem!
something detail
https://github.com/yanfeipeng/btrace/commit/e751e985cb7f0b3776a2b3ed5c1594224197c85d

**Comment by jbachorik** [comment]
Great! Thanks for contributing?

Could you apply the fix to the original `SynchronizedInstrumentor` class (if possible) and then open a PR so I could take the fix upstream?
