### ISSUE TITLE
Why the btrace cannot work

### ISSUE THREAD

**Issue by ezrealliu** [btraceio/btrace#267]
Hi @jbachorik, I have got some problem when I use btrace to trace the code in the prod env. I want to print the args, return value and duration at once,  so I wrote the script like this 
`@OnMethod( clazz='com.wd.demo.StateController', method='queryJVMBrief', location=@Location( value=Kind.CALL, where=Where.AFTER )
public static void args_retVal_drt( @Self Object self, AnyType[] args, @Return Object result, @Duration long duration ){
    println( args );
    println( result );
    println( duration ); 
} 

or like this 

`@OnMethod (clazz='com.wd.demo.StateController', method='queryJVMBrief', location=@Location( value=Kind.RETURN )`  

as the doc. declare, The CALL and RETURN are supported to print out the args, return value and duration when you add AFTER on the annotation. but why it does not  work, the console print nothing. 

Linux version 3.10.0-327.el7.x86_64 gcc version 4.8.3 20140911 (Red Hat 4.8.3-9),  java version "1.7.0_76" btrace version : 1.3.9 
`

**Comment by jbachorik** [comment]
There might be several reasons for not seeing the expected output

* The syntax for `@Location.CALL` is incorrect - you need to provide the call target type and method name - see [this sample](https://github.com/btraceio/btrace/blob/master/samples/AllCalls1.java). When you specify `@Location.CALL` you are saying that you want to intercept certain method invocation from within the specified method - I am not sure this is really what you want to do here.
* The method `queryJVMBrief` is not defined directly by `com.wd.demo.StateController` - eg. it is defined by one of its subclasses
* The method `queryJVMBrief` is static but you are trying to capture the instance variable by `@Self Object self` parameter

I would recommend turning on debug output and capture the instrumented classes (eg. `btrace -v -d <instr_classes_folder> ...`) to get more information and then attach the debug info to this issue.

**Comment by jbachorik** [comment]
Closing due to no response.
