### ISSUE TITLE
Tracing calls with specific calling contexts

### ISSUE THREAD

**Issue by pratikfegade** [btraceio/btrace#271]
Hi,

I am trying to get a log of all the methods called of a set of particular classes (`java.util.*`), from a set of particular classes (say `mypackage.*`). Is it possible to do this? Right now, when I do this, I get internal calls to methods of `java.util.*` too.

For example, if `mypackage.classA` calls `java.util.HashSet.remove()`, which in turn calls `java.util.HashSet.isEmpty()`, I want to dump only the call to `java.util.HashSet.remove()`, and not the call to `java.util.HashSet.isEmpty()`.

Thanks!

**Comment by jbachorik** [comment]
Yes, it is possible. You need to use `Kind.CALL` location. Please, see [the sample code](https://github.com/btraceio/btrace/blob/master/samples/AllCalls1.java) for inspiration.

In your case, the probe point would be defined like
```
 @OnMethod(clazz="myPackage.classA", method="/.*/",   location=@Location(value=Kind.CALL, clazz="/java\\.util\\..*/", method="/.*/"))
```
