### ISSUE TITLE
QUIESTION:can add class field to an class instance?

### ISSUE THREAD

**Issue by jiaqifeng** [btraceio/btrace#276]
I am developing java agent for APM. I have read the jdk doc and find that I could not change an instance of a class. For exapmle:
class Person {
    String name;
    public String getName() {return name;}
}
Persion p=SingletonFactory.get(Persion.class);
...
after p is created, I want to tell the agent to retransform the Person like:
class Persion {
    String name;
    public String getName() {recordNameToTrace();return name;}
}
while instanced p could not using the getName method retransformed as I tested.

Do you known any other way can do it? I am using oracle jdk 1.8

**Comment by jbachorik** [comment]
You are correct that it is not possible to add/remove any fields (static or instance) for any already loaded class.
But the example you are giving is about enhancing a method body with a new method call - and that is permitted. In fact, that's how BTrace can work.
