### ISSUE TITLE
cannot get instance property

### ISSUE THREAD

**Issue by xiaozi** [btraceio/btrace#280]
```
Debug.java:17: error: no suitable method found for get(java.lang.String,java.lang.Object)
	Object obj = get("pageParam", (Object) condition);
	             ^
    method com.sun.btrace.BTraceUtils.<K,V>get(java.util.Map<K,V>,K) is not applicable
      (cannot infer type-variable(s) K,V
        (argument mismatch; java.lang.String cannot be converted to java.util.Map<K,V>))
    method com.sun.btrace.BTraceUtils.get(java.lang.reflect.Field,java.lang.Object) is not applicable
      (argument mismatch; java.lang.String cannot be converted to java.lang.reflect.Field)
error: Debug.java:17:method calls are not allowed - only calls to BTraceUtils are allowed
```

but I see the function is defined here

https://github.com/btraceio/btrace/blob/f6b10d797d02d9c6b256df8efbc15683d27abdd8/src/share/classes/com/sun/btrace/BTraceUtils.java#L6049

**Comment by yardus** [comment]
Can you make sure you are using a recent version of BTrace? The method was added in 1.3.5 and an attempt to compile the script with an older version will confuse the compiler which will try to match the method with [BTraceUtils.get(Map, Object)](https://github.com/btraceio/btrace/blob/f6b10d797d02d9c6b256df8efbc15683d27abdd8/src/share/classes/com/sun/btrace/BTraceUtils.java#L2185)

**Comment by xiaozi** [comment]
@yardus I use the latest version 1.3.9

**Comment by xiaozi** [comment]
I download the 'v1.3.9' release

and unzip the `btrace-boot.jar` and find the file `/com/sun/btrace/BTraceUtils.class`

then I use JD-GUI decompile `BTraceUtils.class`, there is no method `get(java.lang.String,java.lang.Object)`

Should I build btrace myself?

**Comment by jbachorik** [comment]
The method is in `Reflective` scope. Therefore you need to call `BTraceUtils.Reflective.get(name, instance)`

**Comment by xiaozi** [comment]
@jbachorik my fault, thank you
