### ISSUE TITLE
Issue about buffer flushing.

### ISSUE THREAD

**Issue by xinyuan-liu** [btraceio/btrace#281]
I use the jvm agent to trace some small java programs. The output file is empty if the output is short when the program exits. I think this is because the buffer had not been flushed when the program exits.
Is there a method to manually flush the output buffer in the script or some other way to flush the output buffer automaticlly?

I use the following JVM arguments:
-javaagent:/Volumes/Unnamed/btrace/build/btrace-agent.jar=noServer,scriptOutputFile=/Volumes/Unnamed/a.txt,script=/Volumes/Unnamed/btrace/AllLines.class

If the output is short, the output file will only contains a line with date and time.

**Comment by jbachorik** [comment]
Try adding `-Dio.btrace.FileClient.flush=-1` to the JVM arguments. I will take a look about the flushing on exit logic.
