### ISSUE TITLE
I am interested in why don't provide a method in BTraceUtils to println all fields of an object?

### ISSUE THREAD

**Issue by zhenjunMa** [btraceio/btrace#285]
In my applicaiton,  the params of most method is an object , not primitive type.but now so when I want to print the params,  i can only use the codes below:

```
@BTrace 
public class AllMethods {
    @OnMethod(
        clazz="com.xxx.xxxController",
        method="getXXX",
        location=@Location(Kind.RETURN)
    )
    public static void m(AnyType[] args, @Return AnyType result) {
        printArray(args);
        printFields(result);
    }
}
```
this can't recursive print an object!
I am curioused about this design that not provide a method to  recursive println an object....which i think is so easy to implement.

**Comment by jbachorik** [comment]
Yes, it is easy to implement. It's just there hasn't been demand for this functionality yet.
Please, feel free to open a PR with the implementation. Any contributions are greatly welcomed!
