### ISSUE TITLE
jdk1.7 or jdk1.8 about btrace

### ISSUE THREAD

**Issue by chgitcrazy** [btraceio/btrace#290]
hello , when I use btrace to attach the server(jetty or tomcat), I always used the btrace compiled with jdk1.8 ,;
if tomcat server or jetty server use jdk1.7 , and btrace is compiled with jdk1.8, is there any bug?
if tomcat server or jetty server use jdk1.8, and btrace is compiled with jdk1.7, is there any bug?

the java version of btrace and the java version of server must be same?

**Comment by jbachorik** [comment]
No. BTrace probes are always compiled to bytecode compatible with JDK7 as well as the BTrace engine.
And since Java 8 runs classes compiled for Java 7 seamlessly you should not see any compatibility problem.
