### ISSUE TITLE
Pre-process and pre-verify BTrace probes during compilation

### ISSUE THREAD

**Issue by jbachorik** [btraceio/btrace#291]
Currently, the BTrace probes are fully processed and verified on the agent side. The processing and verification requires quite a heavy machinery to be employed and results in loading a bunch of extra classes and doing a lot of extra work. All this translates to pretty high fixed overhead, which can be >500ms per script.

Such high fixed overhead means trouble for situations when we need to instrument many short lived JVMs (cloud, anyone?) as the perceived result is that the execution got n times slower due to BTrace.

The solution is to pre-process the probe code during compilation - we have all the necessary information to do that and extra 500ms during compilation is not such a high price to pay.
However, the pre-processed probe needs some additional metadata to be communicated to BTrace agent so the data format had to be enhanced - and it will not be 100% compatible with Java class file. In order to maintain backward compatibility the agent will still be able to process the old, java class, format, with the extra runtime penalty, of course.

Transferring the already pre-processed probe bytecode makes it impossible to impose all the BTrace restrictions on agent side (using only the bytecode). So, theoretically, it will become possible to hand-craft bytecode which could not be generated by the BTrace compiler (as it still enforces all restrictions).  To minimize the risk, submitting the probes via dynamic attach (using `btrace` command) will still use the original format allowing full verification.
For the startup scripts it will be possible to increase the protection by embedding the script into a signed JAR - in fact, BTrace agent will load embedded scripts only when in signed JAR or the agent is running in `trusted` (= no verification) mode.

**Comment by D3Hunter** [comment]
after this change, it's improssible to build `btrace` with jdk1.7(jdk1.8 works fine), as `javac` prevent access to `com.sun.xml.internal.messaging.saaj.util.ByteOutputStream`

**Comment by jbachorik** [comment]
Filed #323 to track this.
Thanks for reporting - sometimes the IDE autoimport does strange things :/
