### ISSUE TITLE
Is there some plan to support jdk9

### ISSUE THREAD

**Issue by whitelilis** [btraceio/btrace#292]
Is there some plan to support jdk9?

**Comment by yardus** [comment]
Not an immediate one.
The company that pays for my time to spend on BTrace doesn't have JDK 9 support as its priority. Therefore it will happen if there is demand. For the time being it would be nice if community tried the current version with all the JDK 9 command line switches required to open the modules to the BTrace engine and started filing JDK 9 related issues so there is something palpable to work on.

**Comment by jbachorik** [comment]
The support for 9, 10 and 11 is in `develop` branch and will be released in 2.0.0 version.
