### ISSUE TITLE
Passing the class name dynamically to clazz parameter in BTrace script

### ISSUE THREAD

**Issue by Ranganathvk** [btraceio/btrace#298]
@jbachorik  
I need to pass application's package name to btrace script to clazz parameter dynamically when I attach the agent to the jvm,so that I only probe class and  methods of application .How can i achieve this ?

 @OnMethod(
            clazz = "/.*\\.packageName\\..*/",
            method = "/.*/"
    )
    public static void m(@ProbeClassName
                                 String cn, @ProbeMethodName
                                 String mn,
                         AnyType[] args) {
      
    }

**Comment by Tapan2609** [comment]
Facing the same issue as mentioned by @Ranganathvk .....Any help??...

**Comment by jbachorik** [comment]
Fixed in #321 
You can use `@OnMethod(clazz = "/${packageName}\..*/, method = "/.*/")` now - just don't forget to specify the `packageName` user argument when running the probe.
