### ISSUE TITLE
btrace 1.3.10 can not work in JDK 1.8  , help !

### ISSUE THREAD

**Issue by thinkhejie** [btraceio/btrace#307]
btrace 1.3.10 can not work in JDK 1.8  , help !

**Comment by jbachorik** [comment]
I would appreciate more details. Eg. the failure mode or exception.

**Comment by jbachorik** [comment]
Can you try 1.3.10.2?

**Comment by tmohme** [comment]
1.3.10.2 works fine for me on macOS 10.13.2 with Oracle JDK 1.8.0_144-b01.
btw.: I can confirm #305 is solved with 1.3.10.2

**Comment by jbachorik** [comment]
Closing due to no response. Please, reopen if still valid.

**Comment by thinkhejie** [comment]
i want to monitor HashMap resize , java code is below .

but it can not work  in JDK 1.8 .  should i do some right things for this  ?

`
package com.lzy;

import java.util.HashMap;
import java.util.concurrent.TimeUnit;

public class TestJVM {

    public static final int ONE_MB = 1024 * 1024;

    // -javaagent:/Users/hejie/devtool/maven/repository/com/sun/tools/btrace/btrace-agent/1.3.10.1/btrace-agent-1.3.10.1.jar
    //-javaagent:/Users/hejie/devtool/btrace/btrace-agent.jar=dumpClasses=true,dumpDir=/Users/hejie/devtool/btrace/dump,debug=true,stdout=true,unsafe=false,noServer=true,startupRetransform=true,script=/Users/hejie/framework/btraceside/target/classes/com/lzy/BTraceMain.class
    public static void main(String[] args) throws Exception {
        mapExpandCapacity();
    }

    /**
     * java.util.HashMap#resize(int)
     * 
     */
    public static void mapExpandCapacity() throws Exception {
        new Thread(new Runnable() {
            public void run() {
                while (true) {
                    HashMap<Integer, Byte[]> map = new HashMap<Integer, Byte[]>(1, 0.25f);//16,0.75 16*0.75=12
                    int size = 100;
                    for (int i = 0; i < size; i++) {
                        map.put(i, new Byte[ONE_MB]);
                    }
                    System.out.println("Expand SIZE = " + map.size());
                    try {
                        TimeUnit.SECONDS.sleep(10);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }, "mapExpandCapacity").start();
        TimeUnit.HOURS.sleep(1);
    }
}
`

`    
@OnMethod(clazz = "+java.util.HashMap", method = "resize")
    public static void m0(AnyType[] args) {
        println("\n==== +java.util.HashMap#resize ====");
        printArray(args);
        jstack();
    }
`

**Comment by feng-zh** [comment]
Not sure if my local hotfix addressed this issue.

I just start btrace agent mode with script (or script dir), but it appears 1.3.10.2 version did not transform the classes. By looking into debug and source code, it appears the commit bb5ce19 [src/share/classes/com/sun/btrace/agent/Main.java](https://github.com/btraceio/btrace/blob/bb5ce1944efe536340a4afe43fb5cb97e4cf074c/src/share/classes/com/sun/btrace/agent/Main.java) move `addTransformer` function into finally block,

https://github.com/btraceio/btrace/blob/0f37ca3b2e56f6aa599ca2f4439ae0c7a238c453/src/share/classes/com/sun/btrace/agent/Main.java#L146

whic is invoked after `startScripts()` call 

https://github.com/btraceio/btrace/blob/0f37ca3b2e56f6aa599ca2f4439ae0c7a238c453/src/share/classes/com/sun/btrace/agent/Main.java#L112

in `main()` function at [`com.sun.btrace.agent.Main`]( https://github.com/btraceio/btrace/blob/0f37ca3b2e56f6aa599ca2f4439ae0c7a238c453/src/share/classes/com/sun/btrace/agent/Main.java)

The `startScripts` try to load, verify script, and trigger `client.retransformLoaded()` at:
https://github.com/btraceio/btrace/blob/0f37ca3b2e56f6aa599ca2f4439ae0c7a238c453/src/share/classes/com/sun/btrace/agent/Main.java#L616-L619
and `handleNewClient()` is to do real retransform loaded:
https://github.com/btraceio/btrace/blob/0f37ca3b2e56f6aa599ca2f4439ae0c7a238c453/src/share/classes/com/sun/btrace/agent/Main.java#L685-L707

Based on this debug output and finding, I did hotfix  feng-zh/btrace@08d3261 in my forked version, and delay `handleNewClient()` to do retransform after btrace class transformer installed.

Please check if this analysis is addressing this issue. It is simple to reproduce this issue by using samples with "-javaagent" option. And this is impacting btrace javaagent mode after 1.3.10 version.

**Comment by jbachorik** [comment]
Hi, @feng-zh !
Thanks for fixing that problem! The fix looks fine - please, file a proper PR so I can merge.

**Comment by feng-zh** [comment]
@jbachorik, I have created PR #373 to resolve this issue. The PR is based on latest develop branch, and  include your review comments on renaming existing method.
