### ISSUE TITLE
how to trace a application which is run by using tomcat server..

### ISSUE THREAD

**Issue by dineshnagar** [btraceio/btrace#312]
I have create BTrace scripts which are below..

import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

/**
 * This script traces method entry into every method of 
 * every class in javax.swing package! Think before using 
 * this script -- this will slow down your app significantly!!
 */
@BTrace public class BtraceScript{
    @OnMethod(
        clazz="es.asegnz.spring.boot.gradle.sample.*",
        method="/.*/"
    )
    public static void m(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        print(Strings.strcat("entered ", probeClass));
        println(Strings.strcat(".", probeMethod));
    }
}

I want to trace all class and method under "es.asegnz.spring.boot.gradle.sample" package.. run below command.. 
**btrace -p 2020 -cp D:\Btrace\Btrace\build 13876 BtraceScript.class**
2020 :- default port on BTrace agent listens 
D:\Btrace\Btrace\build :- classpath of BTrace 
13876 :- PID of tracing application
BtraceScript.class :- class file of BTrace scripts..

after run above command ** getting below screen..
![console](https://user-images.githubusercontent.com/35604108/35230616-6fa46d84-ff8e-11e7-802c-87230cb01cb5.jpg)

could you please help...

**Comment by jbachorik** [comment]
First step would be running BTrace in verbose mode `btrace -v ...` and attaching the textual output (not just screenshot) here.

**Comment by dineshnagar** [comment]
BTrace v.1.3.9-unravel-2010 (20180122)

**Comment by dineshnagar** [comment]
thanks for the support its working fine i am able to trace tomcat and spring boot application only below changes 
1. changes in scripts 
 @OnMethod(
        clazz="/es\\.asegnz\\.spring\\.boot\\.gradle\\.sample\\..*/",
        method="/.*/"
    )
2. remove class path from command then its working fine i have set class path in BTRACE_HOME in E.V.
btrace -p 2020 4956 BtraceScript.class
2020 port and 4956 is PID and I have used BtraceScript.class

One Question can we get the Btrace trace result in log file if yes so please share the steps..??
