### ISSUE TITLE
how to run CRNK application with jersey Example

### ISSUE THREAD

**Issue by dineshnagar** [btraceio/btrace#314]
I tried to run CRNK application with Jersey-example could you please share steps.
if any one have steps please share...

**Comment by jbachorik** [comment]
What would be the exact problem here? Was BTrace involved in any way?

**Comment by jbachorik** [comment]
Ping. Any more details?
If I don't hear back from you in 7 days I am going to close this issue.

**Comment by jbachorik** [comment]
Closing
