### ISSUE TITLE
tracing inner class

### ISSUE THREAD

**Issue by skrishnamachari** [btraceio/btrace#315]
Can we trace the innerClassTest01..  with annotations..  for clazz / location 

public class TestDynamicInnerClass {

    static public class Class extends java.lang.Object {
        protected Class(){

        }

        public String innerClassTest01(){
            return "Inner Class test01";
        }
    }
}

**Comment by skrishnamachari** [comment]
This works..

  @OnMethod(clazz="com.dynamictrace.TestDynamicInnerClass$Class", method="/.*/" )
              // location=@Location(value=Kind.RETURN)) //, clazz="/.*/", method="/private.*/"))
                //@Sampled(kind = Sampled.Sampler.Adaptive)
    public static void traceTrans02(  @ProbeMethodName String probeMethod ) { 
            logString(probeMethod);
     
    }

**Comment by jbachorik** [comment]
So, is there any problem left resolved?

**Comment by skrishnamachari** [comment]
No it works fine... Just documented it after initial trials to get it
working

On Sat, Feb 17, 2018 at 9:12 AM, Jaroslav Bachorik <notifications@github.com

**Comment by jbachorik** [comment]
Then let me close this issue.
