### ISSUE TITLE
how to monitor hashmap resize happened ?

### ISSUE THREAD

**Issue by thinkhejie** [btraceio/btrace#317]
my java code is below, but it can not work . is the code right ?  thanks very mush.

`
@OnMethod(clazz = "+java.util.HashMap", method = "resize")
    public static void m0(AnyType[] args) {
        println("\n==== +java.util.HashMap#resize ====");
        printArray(args);
        jstack();
    }

public static void mapExpandCapacity() throws Exception {
        new Thread(new Runnable() {
            public void run() {
                while (true) {
                    HashMap<Integer, Byte[]> map = new HashMap<Integer, Byte[]>(1, 0.25f);//16,0.75 16*0.75=12
                    int size = 100;
                    for (int i = 0; i < size; i++) {
                        map.put(i, new Byte[ONE_MB]);
                    }
                    System.out.println("Expand SIZE = " + map.size());
                    try {
                        TimeUnit.SECONDS.sleep(10);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }, "mapExpandCapacity").start();
        TimeUnit.HOURS.sleep(1);
    }
`

**Comment by jbachorik** [comment]
What is the output of running BTrace agent in verbose mode?

Try factoring out the code 
```
int size = 100;
for (int i = 0; i < size; i++) {
  map.put(i, new Byte[ONE_MB]);
}
System.out.println("Expand SIZE = " + map.size());
```
into a separate method to rule out any problems caused by the traced type being always on stack.

**Comment by jbachorik** [comment]
Ping. Did it help?

**Comment by jbachorik** [comment]
No response
