### ISSUE TITLE
Location(kind = Kind.NEWARRAY) dimension  always 1

### ISSUE THREAD

**Issue by hellodengfei** [btraceio/btrace#318]
The sample NewArray.java
 ```
@OnMethod(
      clazz="/.*/", // tracking in all classes; can be restricted to specific user classes
      method="/.*/", // tracking in all methods; can be restricted to specific user methods
      location=@Location(value=Kind.NEWARRAY, clazz="char")
    )
    public static void onnew(@ProbeClassName String pcn, @ProbeMethodName String pmn, String arrType, int dim) {
        // pcn - allocation place class name
        // pmn - allocation place method name
        // **** following two parameters MUST always be in this order
        // arrType - the actual array type
        // dim - the array dimension

        // increment counter on new array
        count++;
    }
```

On JDK7,the dimension always 1

**Comment by jbachorik** [comment]
`Kind.NEWARRAY` arg definitions is a bit confusing now. What it actually provides is the value of `dimensions` parameter for `multianewarray` instruction or 1  for `anewarray` or `newarray` instructions (see https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings for details). Basically, the number is not, as one would expect, the array length(s) but rather its dimension - eg. `int[][]` would return 2, `String[][][]` will yield 3, etc.

**Comment by hellodengfei** [comment]
@jbachorik but how can get the the array length, normally the length is more cared

**Comment by jbachorik** [comment]
I suppose this can be closed as resolved.
