### ISSUE TITLE
Provide support for method parameters for CATH, THROW and ERROR

### ISSUE THREAD

**Issue by jbachorik** [btraceio/btrace#327]
Instrumentation for `Kind.CATCH`, `Kind.THROW` and `Kind.ERROR` should be updated to take the Throwable as a `@TargetInstance` annotated parameter and leave the unannotated probe parameters be filled with the actual method arguments of the probed method.

**Comment by saaavsaaa** [comment]
Such as this?
    @OnMethod(clazz="/.*\\.OnMethodTest/", method="args", location=@Location(value=Kind.ERROR))
    public static void args(@Self Object self, @Return long retVal, @Duration long dur, **String a, long b, String[] c, int[] d**, @TargetInstance Throwable err) {
        println("args");
    }

**Comment by jbachorik** [comment]
@saaavsaaa Yes. With correct capitalization, of course, but the gist is correct.

**Comment by saaavsaaa** [comment]
Is there a unit test about on "String a, long b, String[] c, int[] d"?I want to refer to it.Lately,I try to write unit test like that in InstrumentorTest.java，but I can't write bytecode very well yet.
