### ISSUE TITLE
How to configure btrace in an ant junit xml file?

### ISSUE THREAD

**Issue by hehondou** [btraceio/btrace#328]
I want to use btrace in an ant junit framework, so how to configure the xml file and how to configure the script class file?

**Comment by jbachorik** [comment]
Not sure. I am not an Ant power user. Might be someone else can answer this question.
For one mode of usage in unit tests you can check the BTrace tests sources - unit and the functional ones.

**Comment by jbachorik** [comment]
Was the BTrace functional tests of any help?
I guess you would have better chance of finding the answer on StackOverflow.

Closing.
