### ISSUE TITLE
Hwo to output the print data to a socketserver?

### ISSUE THREAD

**Issue by hehondou** [btraceio/btrace#330]
I am tracing a program for a very long time, and deal with the output file to get some information. But the output file can be very big. So I want to send the print data to a runtime socket server. And I will deal with the received data at the socket server point. Can you help me about how to do that ?

**Comment by jbachorik** [comment]
You can either use BTrace trusted mode (`@BTrace(trusted = true)`) and use Java IO directly or package the streaming output as a BTrace service extension - see eg. https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/services/impl/Printer.java
