### ISSUE TITLE
java.lang.NoClassDefFoundError: Test$1

### ISSUE THREAD

**Issue by chgitcrazy** [btraceio/btrace#332]
I compiled the master branch code，then run my demo！but occured this：

java.lang.NoClassDefFoundError: Test$1
	at java.lang.ProcessImpl.$btrace$Test$exec(ProcessImpl.java)
	at java.lang.ProcessImpl.start(ProcessImpl.java)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at RuntimeTest.main(RuntimeTest.java:6)

My demo code follows as：

import com.sun.btrace.AnyType;
import com.sun.btrace.annotations.*;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import static com.sun.btrace.BTraceUtils.println;
import java.util.concurrent.*;

@BTrace(unsafe = true)
public class Test {
    /*
    remote command execute
     */
    @OnMethod(clazz = "java.lang.ProcessImpl", method = "start")
    public static void exec(@ProbeClassName String pcn, @ProbeMethodName String pmn, String[] cmdarray, Map<String, String> environment, String dir, ProcessBuilder.Redirect[] redirects, boolean redirectErrorStream) {
        Callable callable = new Callable() {
            @Override
            public Object call() throws Exception {
                return null;
            }
        };
        try{
            println(pcn);
            println(pmn);
        }catch (Exception e){
           println(e);
        }
    }

}

from the output ，the Callable class couldn't be found！ why？

**Comment by jbachorik** [comment]
It is not possible to use any nested classes in BTrace script.
If you really need that functionality you will have to either create a support library to include in the bootClassPath or systemClasspath of BTrace agent and either use the trusted mode (`@BTrace(trusted = true)`) or package the utility classes as a BTrace extension service.

**Comment by chgitcrazy** [comment]
Thank you！Got it！
