### ISSUE TITLE
The lastest version code contrains errors when execute "./gradlew build" with jdk1.8.0_162 and gradle 4.7

### ISSUE THREAD

**Issue by hehondou** [btraceio/btrace#334]
> Task :compileJava 
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/profiling/MethodInvocationProfiler.java:43: warning: [ThreadLocalUsage] ThreadLocals should be stored in static fields
    final private ThreadLocal<MethodInvocationRecorder> recorder = new ThreadLocal<MethodInvocationRecorder>(){
                                                                   ^
    (see http://errorprone.info/bugpattern/ThreadLocalUsage)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceRuntime.java:176: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
                e.printStackTrace(System.err);
                ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceRuntime.java:261: warning: [ThreadLocalUsage] ThreadLocals should be stored in static fields
    private ThreadLocal<Throwable> currentException = new ThreadLocal<>();
                                                      ^
    (see http://errorprone.info/bugpattern/ThreadLocalUsage)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceRuntime.java:926: warning: [JdkObsolete] StringBuffer performs synchronization that is usually unnecessary; prefer StringBuilder.
        return threadSafe ? new StringBuffer() : new StringBuilder();
                            ^
    (see http://errorprone.info/bugpattern/JdkObsolete)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceRuntime.java:1777: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
                    ioExp.printStackTrace();
                    ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceRuntime.java:1788: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
                exp.printStackTrace();
                ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/DebugSupport.java:77: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
                exp.printStackTrace();
                ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/ArgsMap.java:44: warning: [StringSplitter] String.split(String) has surprising behavior
                String[] kv = arg.split("=");
                                       ^
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'String[] kv = arg.split("=", -1);'?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/compiler/PCPP.java:136: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            e.printStackTrace();
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/compiler/Compiler.java:60: warning: [JavaLangClash] com.sun.btrace.compiler.Compiler clashes with java.lang.Compiler
public class Compiler {
       ^
  
    (see http://errorprone.info/bugpattern/JavaLangClash)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/compiler/Compiler.java:324: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            e.printStackTrace(perr);
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/compiler/CompilerClassWriter.java:46: warning: [StringSplitter] String.split(String) has surprising behavior
        for(String e : classPath.split(File.pathSeparator)) {
                                      ^
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'for(String e : classPath.split(File.pathSeparator, -1)) {'?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/client/Client.java:471: warning: [StringSplitter] String.split(String) has surprising behavior
        String[] components = javaClassPath.split(File.pathSeparator);
                                                 ^
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'String[] components = javaClassPath.split(File.pathSeparator, -1);'?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/client/Client.java:559: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            iace.printStackTrace();
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/agent/Client.java:495: warning: [StringSplitter] String.split(String) has surprising behavior
            String[] parts = pName.split("@");
                                        ^
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'String[] parts = pName.split("@", -1);'?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/runtime/BTraceClassReader.java:67: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            e.printStackTrace();
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/runtime/BTraceClassReader.java:166: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            e.printStackTrace();
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/runtime/BTraceClassReader.java:199: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            e.printStackTrace();
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/runtime/BTraceClassReader.java:227: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
            e.printStackTrace();
            ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/agent/Main.java:424: warning: [StringSplitter] String.split(String) has surprising behavior
                        String[] parts = p.split(":");
                                                ^
    (see http://errorprone.info/bugpattern/StringSplitter)
  Did you mean 'String[] parts = p.split(":", -1);'?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/agent/TraceOutputWriter.java:231: warning: [CatchAndPrintStackTrace] Logging or rethrowing exceptions should usually be preferred to catching and calling printStackTrace
                e.printStackTrace();
                ^
    (see http://errorprone.info/bugpattern/CatchAndPrintStackTrace)
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:968: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:977: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:986: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:995: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:1004: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:1013: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:1022: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
/home/hondou/applications/btrace/btrace/src/share/classes/com/sun/btrace/BTraceUtils.java:1031: error: [ReturnValueIgnored] Return value of this method must be used
        Arrays.toString(array);
                       ^
    (see http://errorprone.info/bugpattern/ReturnValueIgnored)
  Did you mean to remove this line?
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
21 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
1 actionable task: 1 executed

**Comment by hehondou** [comment]
gradle 4.6 is ok!

**Comment by hehondou** [comment]
src/share/classes/com/sun/btrace/BTraceUtils.java
line: 962 to 1031
In the new added methods of printArray, the code "Arrays.toString(array)" throwns "Return value of this method must be used".
By changing the code above to "String str = Arrays.toString(array);", the errors can be corrected.
But I don't know whether this correctness are meanfuling and useful.

**Comment by jbachorik** [comment]
Will have to check this. Did you change the gradle version or is this failing out of the box?
