### ISSUE TITLE
Can btrace run in the background?

### ISSUE THREAD

**Issue by 15993061515** [btraceio/btrace#339]
I use Xshell to link the server and use btrace to monitor the java application.But one hour later,my xshell has been killed。so Can btrace run in the background?

**Comment by jbachorik** [comment]
If you want to use dynamic attach then the only option would be `nohup` or `tmux` or similar utility.
Of course, you can attach BTrace agent on JVM startup via `-javaagent` argument and then BTrace will be running as long as the target JVM.
