### ISSUE TITLE
sometimes ctrl-c and select exit will cause jvm throw java.lang.NoSuchMethodError and crash

### ISSUE THREAD

**Issue by litao-buptsse** [btraceio/btrace#344]

**Comment by zhaikaishun** [comment]
I have the same problem 
My Java Code  
```
package me.zks.jvm.troubleshoot.btrace;
import java.util.concurrent.TimeUnit;
public class FirstSample {
    public static void main(String[] args) {
        FirstSample firstSample = new FirstSample();
        while (true){
            firstSample.fun1("aa","bb");
        }
    }
    public void fun1(String str1,String str2){
        try {
            System.out.println("fun1 para is:"+str1+","+str2);
            String result = fun2(str2);
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
    private String fun2(String str2) {
        System.out.println("fun2 para is:"+str2);
        return "fun2"+str2;
    }
}
```
And the trace is  
```
import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.*;
@BTrace
public class FirstSampleBtrace {
//    @OnMethod(
//            clazz = "me.zks.jvm.troubleshoot.btrace.FirstSample"
//            ,method = "fun1"
//            ,location = @Location(value = Kind.ENTRY))
//    public static void m(@Self Object self,String str1,String str2){//,String str2
//        BTraceUtils.print("fun1 str1:"+str1+" str2: "+str2);
//    }

    @OnMethod(clazz = "me.zks.jvm.troubleshoot.btrace.FirstSample",
            method = "fun2",
            location = @Location(value = Kind.ENTRY))
    public static void m1(@Self Object self,String str1){
        BTraceUtils.print("fun2 str1:"+str1+" ");
    }

    @OnMethod(clazz = "me.zks.jvm.troubleshoot.btrace.FirstSample",
            method = "fun1",
            location = @Location(value = Kind.RETURN))
    public static void m2(@Self Object self,String str1,String str2,@Return Void a,@Duration long time){
        BTraceUtils.print("fun1 str1:"+str1+" str2:"+str2+" Duration is: "+time+" ");
    }

}
```
And It's Throw Exception  
```
Exception in thread "main" java.lang.NoSuchMethodError: me.zks.jvm.troubleshoot.btrace.FirstSample.$btrace$me$zks$jvm$troubleshoot$btrace$FirstSampleBtrace$m2(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Void;J)V
	at me.zks.jvm.troubleshoot.btrace.FirstSample.fun1(Unknown Source)
	at me.zks.jvm.troubleshoot.btrace.FirstSample.main(Unknown Source)
```

**Comment by jbachorik** [comment]
The culprit is infinite loop in your main method. The method 'fun1' got (most probably) inlined to 'main' and that method being in infinite loop JVM does not have a chance to replace the method definition - while, in the meantime, it already successfully removed the BTrace helper methods from the instrumented class.

If this is happening in real-life applications and not just some examples the only way to fix this would be to never remove the BTrace helper methods from the instrumented classes.

**Comment by rockjl** [comment]
我也碰到了同样的问题。是否可以使用try-catch包裹已经插入到OnMethod目标方法的代码。java.lang.NoSuchMethodError。这样的话至少不会导致调试的应用异常退出。

**Comment by rockjl** [comment]
`Compiled from "TestBt.java"
public class TestBt {
  public TestBt();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: new           #2                  // class TestBt$A
       3: dup
       4: invokespecial #3                  // Method TestBt$A."<init>":()V
       7: invokevirtual #4                  // Method TestBt$A.start:()V
      10: return

  public java.lang.String thread_process(int);
    Code:
       0: getstatic     #5                  // Field java/lang/System.out:Ljava/io/PrintStream;
       3: iload_1
       4: invokevirtual #6                  // Method java/io/PrintStream.println:(I)V
       7: invokestatic  #7                  // Method slee:()V
      10: iload_1
      11: invokedynamic #8,  0              // InvokeDynamic #0:makeConcatWithConstants:(I)Ljava/lang/String;
      16: dup
      17: astore_2
      18: iload_1
      19: ldc           #72                 // String TestBt
      21: ldc           #73                 // String thread_process
      23: aload_2
      24: invokestatic  #77                 // Method $btrace$BtraceScript$thread_process:(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
      27: areturn
}`

是否可以使用try-catch块包裹“24: invokestatic  #77                 // Method $btrace$BtraceScript$thread_process:(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V”这行代码？？？在没有异常发生的时候try-catch块的性能几乎是可以忽略不计的。但是如果测试的目标应用异常退出的话，会导致很严重的后果的。
