### ISSUE TITLE
can btrace implement hot swap？

### ISSUE THREAD

**Issue by chgitcrazy** [btraceio/btrace#346]
Today， I use btrace to debug my Application ,in the process ,I suddenly have an idea that if the btrace-agent.jar injected to the server could be unload ,then I wonldn't restart the server every time!
If so , I could use btrace to load and unload btrace-agent.jar to the process withouting restart it . It will be more convinient !  Is there any solution?

**Comment by jbachorik** [comment]
When using dynamic attach (`btrace <pid> <trace script>`) the instrumentation is removed once the session is closed. The agent remains in the JVM but it is basically just a socket listener for accepting new tracing sessions. With this approach you don't need to restart the server when you change the instrumentation.

If you attach the agent on startup (as JVM `-javaagent` argument) then this mode of operation is (almost) possible too. The only difference is that whatever script is loaded with the agent will stay there forever. But you still can attach and detach to the server JVM later on.

**Comment by chgitcrazy** [comment]
Thank you ！yeah ，I  don't need to restart the server when I change the instrumentation. But if I want to change the function in the agent，is there any method？Such as adding a new Command；Because the Command function is loaded by bootclassloader，it's have no chance to be unload；The only method is restart the server！

**Comment by jbachorik** [comment]
Not really. This would require a fully-functional plugin system with plugin hotswap which is a pretty complicated thing to do. And considering the nature of the JVM agents this would be very susceptible to interference from the traced application - not even mentioning the unintended side effects such a complex agent might have on the traced application itself.

What it is you are trying to achieve?

**Comment by chgitcrazy** [comment]
I want to achieve the function that could monitor and trace the Classes and Methods .
Besides，the function can be wrapper into a hotswap plugin to have no effect on the server（tomcat...) .Because I am afraid that the server would be affected by the code inused in the memory.

**Comment by jbachorik** [comment]
What about [Adaptive Instrumentation](https://github.com/btraceio/btrace/wiki/Adaptive-Instrumentation) - would that solve your problem?

**Comment by TJ2572208413** [comment]
i don't know
