### ISSUE TITLE
Invalid 'libs' configuration [null]

### ISSUE THREAD

**Issue by UnitedMarsupials** [btraceio/btrace#347]
Every time I attach btrace to a Java-process, a message like that below appears in the process' log:

`[Attach Listener] console : ERROR - btrace WARNING: Invalid 'libs' configuration [null]. Path '... path to BTRACE_HOME .../build/btrace-libs' does not exist.`

If this is harmless, the message should be suppressed. If it is important, the attaching should, probably, fail.

At any rate, where is the `build/btrace-libs/`? The only contents of `build/`, as just extracted from [btrace-bin-1.3.11.tgz.tar.gz](https://github.com/btraceio/btrace/releases/download/v1.3.11/btrace-bin-1.3.11.tgz.tar.gz) is:

> build/:
> btrace-agent.jar  btrace-boot.jar  btrace-client.jar  i386

> build/i386:
> libbtrace.so

Please, advise. Thank you!

**Comment by jbachorik** [comment]
Hi, this is harmless, if a bit annoying message.
Will be fixed but till then, please, ignore it.
