### ISSUE TITLE
Could I use btrace to track methods in sun.misc.Unsafe?

### ISSUE THREAD

**Issue by kuaiwei** [btraceio/btrace#348]
I could use btrace script to trace other java methods. But when I try to trace sun.misc.Unsafe::allocateMemory or sun.misc.Unsafe::freeMemory, I can not get output. Can you tell me if it's a limit of btrace?

**Comment by jbachorik** [comment]
Unfortunately, no. `Unsafe` is a protected class for BTrace - we can't instrument it since we strongly depend on that class. Also, this particular method is 'native' and BTrace does not support native method instrumentation.
