### ISSUE TITLE
./gradlew buildDistribution can not resolve nebula.ospackage

### ISSUE THREAD

**Issue by hehondou** [btraceio/btrace#350]
@jbachorik 
When execute ./gradlew buildDistribution, error occurred as "can not resolving plugin [id: 'nebula.ospackage', version: '4.3.0']". 
The reason is that nebula.ospackage.gradle.plugin-4.3.0.jar can not be downloaded at https://plugins.gradle.org/m2/nebula/ospackage/nebula.ospackage.gradle.plugin/4.3.0/nebula.ospackage.gradle.plugin-4.3.0.jar

**Comment by hehondou** [comment]
@joachimhs

**Comment by jbachorik** [comment]
Sorry, the plugin seems to be broken - filed issue there (https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/298)
