### ISSUE TITLE
Tracing program remotely

### ISSUE THREAD

**Issue by gawaine1988** [btraceio/btrace#358]
Hello, I have question about how to trace a program that is running on a remote server. 
I have read the src-code about how to establish a socket-connection between btrace-client and btrace-agent. However the   btrace-agent‘s ip which the client should connect to is written directly in the java code. It seems that btrace do not support  tracing a program remotely.

If so, I suggest that the ip which  the client should connect to could be read from the command line. And, the btrace could trace the remote program.

**Comment by jbachorik** [comment]
This has been addressed in #359 - right?
