### ISSUE TITLE
retransfromClasses could add method？

### ISSUE THREAD

**Issue by chgitcrazy** [btraceio/btrace#364]
hello， by using btrace to hook java.lang.ProcessImpl class，then I dump this class，I found it has added serveral methods such as "$btrace$com$test$Test$testEvent"
but according to the oracle java doc，has documented the follows:
"The retransformation must not add, remove or rename fields or methods, change the signatures of methods, change modifiers, or change inheritance."(https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#Retransform)

is there any trick？
Hope to your answer @oschrenk @joachimhs @marschall @jbachorik @tmohme

**Comment by jbachorik** [comment]
Yes. Hotspot JVM supports adding `private static` methods even though it is not in JVM spec.
