### ISSUE TITLE
java.lang.NoSuchMethodError: com.sun.btrace.BTraceRuntime.init

### ISSUE THREAD

**Issue by feelgood3000** [btraceio/btrace#365]
when i run the script "btrace 1491 AllMethods.class"
my console show follow tips:
Exception in thread "Thread-0" java.lang.NoSuchMethodError: com.sun.btrace.BTraceRuntime.init(Lcom/sun/btrace/PerfReader;Lcom/sun/btrace/RunnableGenerator;)V
at com.sun.btrace.agent.Client.(Client.java:94)
at com.sun.btrace.agent.Main.startServer(Main.java:379)
at com.sun.btrace.agent.Main.access$000(Main.java:65)
at com.sun.btrace.agent.Main$3.run(Main.java:166)
at java.lang.Thread.run(Thread.java:748)
AllMethods.java
@BTrace public class AllMethods { @OnMethod( clazz = "com.demo.btrace.Demo", method = "test", location = @Location(Kind.RETURN) ) public static void m(@Return long sum){ println("test"); } }
Demo.java
`public class Demo {

public static void main(String[] args){

    Demo demo=new Demo();
    for (int i = 0; i < 1000; i++) {
        try {
            Thread.sleep(1000*5);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        demo.test();
    }
}

public static long count=0;

public long test(){
    count++;
    return count;
}
}`

btrace --version
BTrace v.1.3.1 (20150625)

**Comment by jbachorik** [comment]
Can you try with the latest version 1.3.11.1? There were a lot of fixes and improvements since 1.3.1

**Comment by jbachorik** [comment]
No response

**Comment by scutlxp** [comment]
I have try with the latest version 1.3.11.3. the same error still exist

**Comment by 172184221** [comment]
me too
