### ISSUE TITLE
Relax class transformation synchronization

### ISSUE THREAD

**Issue by jbachorik** [btraceio/btrace#369]
BTraceTransformer is synchronizing on `transform` method, possibly leading to deadlocks.
The solution would be relaxing the semantics and use `ReentrantReadWriteLock` - the write lock is necessary for the transformer setup and transform methods can, in fact, run fully concurrently, using read lock.

**Comment by chgitcrazy** [comment]
do you have some deadlocks cases?

**Comment by jbachorik** [comment]
Yes, experienced deadlocks on Spark 2.3 - the probes are close-source so I can not share more.

**Comment by chgitcrazy** [comment]
OK,understand it ,Thank you

**Comment by shidongwa** [comment]
> Yes, experienced deadlocks on Spark 2.3 - the probes are close-source so I can not share more.

Hi Jaroslav, could you please describe your deadlock case ( code  not need)? I am wondering if you have customized   and defined ClassLoader like us :)

**Comment by jbachorik** [comment]
Most probably. It is happening when spark engine is loading some classes it is defining on the fly.
