### ISSUE TITLE
btrace client socket client stuck

### ISSUE THREAD

**Issue by devwebcl** [btraceio/btrace#376]
When trying to call btrace to a weblogic with:

`./btrace -v 22658 TracingScript.java`

I get the following output:

```
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling TracingScript.java
DEBUG: compiled TracingScript.java
DEBUG: attaching to 22658
DEBUG: checking port availability: 2020
DEBUG: attached to 22658
DEBUG: loading /home/btrace-master/build/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=/WLS12c/jdk/lib/tools.jar,probeDescPath=.
DEBUG: loaded /btrace-master/build/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command: []
```
Then checking thread dump, it is stuck at:

https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/client/Client.java#L402

` ois = new ObjectInputStream(sock.getInputStream());`

In my laptop works as expected, but in another server I get stuck at that line.

It looks like to be related to "port not open". Not sure if it's related to localport,  but I don't find a way to change localport.

**Comment by ougyou** [comment]
introduce the professional tools for you, it's easy to do anything  with no coding.
https://github.com/alibaba/arthas

**Comment by jbachorik** [comment]
@ougyou What does this comment help with the reported issue?

**Comment by jbachorik** [comment]
When you do `btrace -h` you will get the usage.
You can specify the port via `btrace -p`

**Comment by devwebcl** [comment]
yes, I have used that argument, but I received a message that port was already in use for btrace.

well, after restarting it is working again.

thanks for the quick answer.

**Comment by ougyou** [comment]
> @ougyou What does this comment help with the reported issue?

no help for the issue, just want to help devwebcl with  the easy tools to slove the problem. 

@jbachorik   firstly, i have no idea to promote the tool,. because i used  btrace for just 2 years ago,
it's usually for me that  i have no choice but to coding to find the bugs that caused by some wrong value or etc...

**Comment by devwebcl** [comment]
thanks for the help.
I didn't know arthas either. it looks good.
