### ISSUE TITLE
The Function and Interpretation of @ Location AnnotationLocation

### ISSUE THREAD

**Issue by xigua1996** [btraceio/btrace#379]
Looking through many blogs, there is no corresponding @Location annotation function and explanation. Would it be convenient for you to talk about it here? Thank you very much and look forward to communicating with you.

**Comment by jbachorik** [comment]
Is javadoc unclear? Can it be improved somehow?
https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/annotations/Location.java

**Comment by jbachorik** [comment]
Any followup to that doc? If not, I will close this ticket in 48 hours.
