### ISSUE TITLE
different behaviour on different 3rd jar

### ISSUE THREAD

**Issue by xiongqisong** [btraceio/btrace#383]
I make a test: see if any code call any method in org.apache.commons.lang3.StringUtils, i write a program to be tracked, when it use commons-lang3 v3.8.1 (StringUtils in the jar), btrace script can't do the right tracking, but when if change the version to v3.2.1, the script work right.
I'm really confuse about btrace, why trace the same class in different version, it show me different behaviour, expecially one work ,one not work ?!
PS: v3.8.1 commons-lang3 was deploy to Maven Central in 2018, and v.3.2.1 was 2014
My btrace script downside:
@OnMethod(clazz = "org.apache.commons.lang3.StringUtils",  location = @Location(value = Kind.LINE,line=-1))
    public static void func() {
        println("StringUtils");
    }

**Comment by jbachorik** [comment]
For line based tracing the class must be compiled with debug info including the line numbers.
Apparently, the 3.8.1 is not compiled with the debug info.

**Comment by xiongqisong** [comment]
OMG, thank you, this problem bothered me for days.
The comment statement of Location doesn't explain this circumstance clearly, so when i write scipt i will think it will work in  any CLASS, could you please adjust the comment statement when you are convienient, i learn btrace so much time, but i feel it's document not very well in spite of it's powerful to trace the code.
Appreciate agein ; )
