### ISSUE TITLE
Transform class error

### ISSUE THREAD

**Issue by xiongqisong** [btraceio/btrace#384]
Here is stack:
btrace DEBUG: parsed command line arguments
btrace DEBUG: Bootstrap ClassPath: .
btrace DEBUG: ignoring boot classpath element '.' - only jar files allowed
btrace DEBUG: System ClassPath: D:\jdk_8u144\jre/../lib/tools.jar
btrace DEBUG: debugMode is true
btrace DEBUG: probe descriptor path is .
btrace DEBUG: stdout is false
btrace DEBUG: starting agent thread
btrace DEBUG: Agent init took: 17603965ns
btrace DEBUG: starting server at 2020
btrace DEBUG: waiting for clients
btrace DEBUG: client accepted Socket[addr=/127.0.0.1,port=61153,localport=2020]
btrace DEBUG: got instrument command
btrace DEBUG: loading BTrace class
btrace DEBUG: verifying BTrace class ...
btrace DEBUG: BTrace class com.xqs.hotfix.btrace.Demo verified
btrace DEBUG: preprocessing BTrace class com.xqs.hotfix.btrace.Demo ...
btrace DEBUG: ... preprocessed
btrace DEBUG: loaded 'com.xqs.hotfix.btrace.Demo' successfully
btrace DEBUG: creating BTraceRuntime instance for com.xqs.hotfix.btrace.Demo
btrace DEBUG: created BTraceRuntime instance for com.xqs.hotfix.btrace.Demo
btrace DEBUG: sending Okay command
btrace DEBUG: client com.xqs.hotfix.btrace.Demo: got com.sun.btrace.comm.OkayCommand@2509be83
btrace DEBUG: about to defineClass com/xqs/hotfix/btrace/Demo
btrace DEBUG: defineClass succeeded for com.xqs.hotfix.btrace.Demo
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/agent/RemoteClient$1
btrace DEBUG: starting client command handler thread
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/agent/Main$3
btrace DEBUG: skipping transform for BTrace class java/lang/instrument/UnmodifiableClassException
btrace DEBUG: new Client created com.sun.btrace.agent.RemoteClient@6c9083b
btrace DEBUG: retransforming loaded classes
btrace DEBUG: filtering loaded classes
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassCache$Singleton
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$ClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$JavaClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$BaseClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/ClassInfo$InternalClassName
btrace DEBUG: skipping transform for BTrace class com/sun/btrace/runtime/BTraceClassReader$BailoutException
btrace DEBUG: candidate class org.apache.commons.lang3.StringUtils added
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/parser/SignatureParser
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/TypeArgument
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/TypeTree
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/Tree
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/SimpleClassTypeSignature
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/FieldTypeSignature
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/BaseType
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/TypeSignature
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/ReturnType
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/tree/ClassTypeSignature
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/scope/ClassScope
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/scope/Scope
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/scope/AbstractScope
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/factory/CoreReflectionFactory
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/factory/GenericsFactory
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/visitor/Reifier
btrace DEBUG: skipping transform for BTrace class sun/reflect/generics/visitor/TypeTreeVisitor
btrace DEBUG: skipping transform for BTrace class sun/reflect/annotation/AnnotationType$1
btrace DEBUG: skipping transform for BTrace class sun/reflect/annotation/ExceptionProxy
btrace DEBUG: skipping transform for BTrace class sun/reflect/annotation/AnnotationTypeMismatchExceptionProxy
btrace DEBUG: skipping transform for BTrace class sun/reflect/annotation/AnnotationParser$1
btrace DEBUG: skipping transform for BTrace class sun/reflect/annotation/AnnotationInvocationHandler
btrace DEBUG: client com.xqs.hotfix.btrace.Demo: got com.sun.btrace.comm.RetransformationStartNotification@4f05f3e7
btrace DEBUG: calling retransformClasses (1 classes to be retransformed)
btrace DEBUG: Attempting to retransform class: org.apache.commons.lang3.StringUtils
btrace DEBUG: transformed class org.apache.commons.lang3.StringUtils
btrace DEBUG: verification error: org.apache.commons.lang3.StringUtils
btrace DEBUG: waiting for clients

========================================
The stack shows transform class error, but btrace don't print error stack, WHY?!
Hope for reply, Thank you ; )

**Comment by xiongqisong** [comment]
private static void handleNewClient(final Client client) {
        serializedExecutor.submit(new Runnable() {

            public void run() {
                try {
                    if (isDebug()) debugPrint("new Client created " + client);
                    if (client.shouldAddTransformer()) {
                        client.registerTransformer();
                        Class[] classes = inst.getAllLoadedClasses();
                        ArrayList<Class> list = new ArrayList<Class>();
                        if (isDebug()) debugPrint("filtering loaded classes");
                        for (Class c : classes) {
                            if (inst.isModifiableClass(c) &&
                                client.isCandidate(c)) {
                                if (isDebug()) debugPrint("candidate " + c + " added");
                                list.add(c);
                            }
                        }
                        list.trimToSize();
                        int size = list.size();
                        if (isDebug()) debugPrint("added as ClassFileTransformer");
                        if (size > 0) {
                            classes = new Class[size];
                            list.toArray(classes);
                            client.startRetransformClasses(size);
                            if (isDebug()) {
                                for(Class c : classes) {
                                    try {
                                        inst.retransformClasses(c);
                                    } catch (VerifyError e) {
                                        debugPrint("verification error: " + c.getName());
                                    }
                                }
                            } else {
                                inst.retransformClasses(classes);
                            }
                            client.skipRetransforms();
                        }
                    }
                    client.getRuntime().send(new OkayCommand());
                } catch (UnmodifiableClassException uce) {
                    if (isDebug()) {
                        debugPrint(uce);
                    }
                    client.getRuntime().send(new ErrorCommand(uce));
                }
            }
        });
        
    }
===================================
I read the origin code of btrace agent, when it transfrom class and there occur an Error, btrace choose to eat the Error and print just a single DEBUG line, that's to rude and confuse programer, could you please explain why do this?
Hope for reply, thank you

**Comment by jbachorik** [comment]
The problem is that `VerificationError` does not provide any details nor stacktrace. Therefore there is  nothing else to display, unfortunately.

**Comment by xiongqisong** [comment]
Thank you for reply.
The problem is obvious, but my problem is why not show the details or stacktrace, so community can provide btrace or jdk with defects (in Instrumentation).
I meet this problem when i practise in writing btrace script, when it happens i can do nothing except feel strange~That's too bad
Appreciate again ; )
