### ISSUE TITLE
NullPointerException&IllegalArgumentException  help help help!!!!!

### ISSUE THREAD

**Issue by llx206** [btraceio/btrace#386]
btrace version:btrace-bin-1.3.8.3.tgz
monitor java:
package com.sogou.btrace;

public class MyBtraceTest { 

    public void execute() {  
        int i = (int) (Math.random() * 1000);  
        System.out.println(i);  
        try {  
            Thread.sleep(Math.abs(i));  
        } catch (InterruptedException e) {  
            e.printStackTrace();  
        }  
    }  
  
    public void loopExcute() {  
        while (true) {  
            execute();  
        }  
    }  
  
    public static void main(String[] args) {  
        MyBtraceTest m = new MyBtraceTest();  
        m.loopExcute();  
    }  

} 

btrace script:
package com.sogou.test.classloader;

import static com.sun.btrace.BTraceUtils.jstack;  
import static com.sun.btrace.BTraceUtils.println;  
import static com.sun.btrace.BTraceUtils.str;  
import static com.sun.btrace.BTraceUtils.strcat;  
import static com.sun.btrace.BTraceUtils.timeMillis;  
  
import com.sun.btrace.annotations.BTrace;  
import com.sun.btrace.annotations.Kind;  
import com.sun.btrace.annotations.Location;  
import com.sun.btrace.annotations.OnMethod;  
import com.sun.btrace.annotations.TLS;  
  
@BTrace  
public class TraceMethodTime {  
  
    @TLS  
    static long beginTime;  
  
    @OnMethod(clazz = "com.sogou.btrace.MyBtraceTest", method = "execute")  
    public static void traceExecuteBegin() {
        println("method start!");  
        beginTime = timeMillis();  
    }  
   
    @OnMethod(clazz = "com.sogou.btrace.MyBtraceTest", method = "execute", location = @Location(Kind.RETURN))  
    public static void traceExcute() {  
        println(strcat(strcat("com.sogou.btrace.MyBtraceTest.execute time is:", str(timeMillis() - beginTime)), "ms"));  
        println("method end!");  
        jstack();
    }  
}

MyBtraceTest startup method:
Java -cp classloader-0.0.1-SNAPSHOT-jar-with-dependencies.jar
com.sogou.btrace.MyBtraceTest > 1 &

After running the MyBtraceTest program, execute
/search/odin/btrace/bin/btrace pid /search/odin/btrace/TraceMethodTime.java

The following error occurred:
java.lang.NullPointerException
        At com.sun.btrace.agent.Client.retransformLoaded(Client.java:389)
        At com.sun.btrace.agent.Client.onExit(Client.java:203)
        At com.sun.btrace.agent.RemoteClient.onCommand(RemoteClient.java:141)
        At com.sun.btrace.agent.Client.errorExit(Client.java:294)
        At com.sun.btrace.agent.Client.loadClass(Client.java:234)
        At com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:64)
        At com.sun.btrace.agent.Main.startServer(Main.java:512)
        At com.sun.btrace.agent.Main.access$000(Main.java:58)
        At com.sun.btrace.agent.Main$2.run(Main.java:119)
        At java.lang.Thread.run(Thread.java:745)
! ERROR
java.lang.IllegalArgumentException
        At com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        At com.sun.btrace.org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        At com.sun.btrace.org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
        At com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:81)
        At com.sun.btrace.runtime.BTraceProbe.<init>(BTraceProbe.java:92)
        At com.sun.btrace.runtime.BTraceProbeFactory.createProbe(BTraceProbeFactory.java:50)
        At com.sun.btrace.agent.Client.load(Client.java:365)
        At com.sun.btrace.agent.Client.loadClass(Client.java:228)
        At com.sun.btrace.agent.RemoteClient.<init>(RemoteClient.java:64)
        At com.sun.btrace.agent.Main.startServer(Main.java:512)
        At com.sun.btrace.agent.Main.access$000(Main.java:58)
        At com.sun.btrace.agent.Main$2.run(Main.java:119)
        At java.lang.Thread.run(Thread.java:745)
Last:
How to locate the problem, thank you very much for your answers!

**Comment by jbachorik** [comment]
Could you try with the latest version first? https://github.com/btraceio/btrace/releases/tag/v1.3.11.3

**Comment by jbachorik** [comment]
Closing due to reporter inactivity
