### ISSUE TITLE
@OnProbe use a regular expression

### ISSUE THREAD

**Issue by Miolover** [btraceio/btrace#388]
can i use a regular expression with @OnProbe？
like this 
 <  probe name="server-socket-creator">
    < map>
        < clazz>/monitor\\.app\\..*/< /clazz>
        < method>/.*/< /method>
        < location>
            < value>RETURN< /value>
        < /location>
    < /map>
 < /probe>

**Comment by jbachorik** [comment]
This should work. Have you tried it?

**Comment by Miolover** [comment]
I tried it used "debug"
1.I Modify the source code.code add a little debugPrint. I find it necessary to add two “//” to use regex.
![IMG_1082](https://user-images.githubusercontent.com/18145191/60868644-07a00b00-a260-11e9-8fc9-b7a9f21cb5b5.JPG)
when i try "// //".it is ok.the regex flag change true.  if "/ /" the regex flag is false
![IMG_2314](https://user-images.githubusercontent.com/18145191/60868832-65345780-a260-11e9-8a3e-f5c753ca5f0e.JPG)
but it does not work, i can't find the Reason.
2.it‘s ok used OnMethod
![IMG_5388](https://user-images.githubusercontent.com/18145191/60871261-f9082280-a264-11e9-8a42-5e95814d7fbb.JPG)
it's skip all classes uesd OnProbe
![IMG_2318](https://user-images.githubusercontent.com/18145191/60871500-792e8800-a265-11e9-97bd-b80ebf020d01.JPG)

**Comment by jbachorik** [comment]
The problem is with `\\` - this is required only in Java since `\` is an escape character. 
In XML you should have something like `//com\..*//`. I have tested `@OnProbe` with corrected regex in XML and it is working as expected.

**Comment by jbachorik** [comment]
Closing as resolved.
