### ISSUE TITLE
debug stop at “DEBUG: sending instrument command: []”

### ISSUE THREAD

**Issue by terryliu1994** [btraceio/btrace#389]
in debug model，the log stop at “DEBUG: sending instrument command: []”
The normal condition is 

![image](https://user-images.githubusercontent.com/30610585/60424841-c4241c00-9c23-11e9-8fdd-14e27cb77916.png)

**Comment by jbachorik** [comment]
What do you mean 'debug mode' - the screenshot is showing BTrace running in 'verbose' mode which is in fact the debug mode.
Can you please, elaborate?

**Comment by jbachorik** [comment]
PING
There really is not enough information to reproduce/debut this report.
