### ISSUE TITLE
not work when OnMethod on some class

### ISSUE THREAD

**Issue by beijibing** [btraceio/btrace#392]
v.1.3.11.3
openjdk version "1.8.0_202"
CentOS Linux release 7.3.1611 (Core) 

**not work**: all my business classes and some other class from thridparty

    @OnMethod(clazz = "org.apache.commons.pool2.impl.GenericObjectPool",
            method = "/.*/",
            location = @Location(Kind.ENTRY))
    public static void returnObject(@ProbeMethodName(fqn = true) String probeMethod,
                                    @Self Object ths) {
        println("invoke: " + probeMethod + ", this: " + BTraceUtils.identityHashCode(ths));
    }

while some classes work well, such as redis.clients.jedis.ShardedJedis(redis.clients:jedis-3.0.1). but on another same machine, not work

**Comment by jbachorik** [comment]
This should work. Can you run BTrace in debug mode and see what is the output? It should give more info about which classes it checks and which ones get instrumented.

**Comment by jbachorik** [comment]
Closing due to reporter inactivity
