### ISSUE TITLE
Can btrace trace the function call when starting up the java application?

### ISSUE THREAD

**Issue by 2994186010** [btraceio/btrace#393]
From the **Running** example,  we need the pid of the java application before running it. I want to trace the function call when starting up the java application. However, when starting up the java application,  we can not know the pid of the java application. So I am curious about whether btrace can trace the function call when starting up the java application. For example, we can consider the brace as the parameter when starting up the java application, such as "java -javaagent:btrace.jar -jar myapp.jar"

**Comment by 2994186010** [comment]
I find **Starting Application with BTrace** in the wiki of btrace, it can trace the code executed very early in the application's lifecycle. The syntax for starting an application with BTrace agent is as following.
`java -javaagent:btrace-agent.jar=[<agent-arg>[,<agent-arg>]*]? <launch-args>`
My java application is deployed as a jar file. And my btrace script is as following.
`import com.sun.btrace.annotations.*;
import static com.sun.btrace.BTraceUtils.*;

/**
 *  * This script traces method entry into every method of 
 *   * every class in javax.swing package! Think before using 
 *    * this script -- this will slow down your app significantly!!
 *     */
@BTrace public class AllMethods {
    @OnMethod(
        clazz="/.*/",
        method="/.*/"
    )
    public static void m(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        print(Strings.strcat("entered ", probeClass));
        println(Strings.strcat(".", probeMethod));
    }
}`
From the syntax above, I don't know where to place the my jar file and btrace script in the command. Who can help me?

**Comment by AnubhavGupta95** [comment]
You can specify full path for jar and btrace script while running the command.

**Comment by jbachorik** [comment]
These links should have all the answers.

https://github.com/btraceio/btrace/wiki#starting-application-with-btrace
https://github.com/btraceio/btrace/wiki/btracer
