### ISSUE TITLE
Unable to open socket file: target process not responding or HotSpot VM not loaded

### ISSUE THREAD

**Issue by AnubhavGupta95** [btraceio/btrace#395]
Here are the logs:-

./btrace -v 21752 ../../WebServiceTracker.java
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling ../../WebServiceTracker.java
DEBUG: compiled ../../WebServiceTracker.java
DEBUG: attaching to 21752
Unable to open socket file: target process not responding or HotSpot VM not loaded

-------------------------------------------------------------------------

Java Version:-
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

------------------------------------------------------------------------

Please guide what am i doing wrong.

**Comment by TimKack** [comment]
Sounds like the btrace agent wasn't injected properly. In your target application, do you see any debug messages coming to stdout? 
Another thing to check is whether the btrace agent socket can be accessed by the user running the `./btrace -v 21752 ...` script, i.e. if the target application runs as the same user?

**Comment by jbachorik** [comment]
@AnubhavGupta95 Did the suggestion resolve your problems?
