### ISSUE TITLE
Linux launch script has incorrect option

### ISSUE THREAD

**Issue by ivenhov** [btraceio/btrace#405]
Hi

I think btrace and btracec scripts have incorrect option.

if [ -f "${JAVA_HOME}/jre" ]; then
should be
if [ -e "${JAVA_HOME}/jre" ]; then

-f is for 'regular file' . I think on Linux a directory is not a regular file, therefore launching btrace fails.

Also I'm not sure why jre directory needs to be checked since scripts are looking for tools.jar or classes.jar.
This seems to be redundant.

**Comment by jbachorik** [comment]
It's not really redundant. The whole block is valid only for MacOS and if, after few attempts to locate `tools.jar` in well known locations the `TOOLS_JAR` var is still empty the script will exit, virtually making it impossible to run on newer Java (9+) distributions where there is no JRE and not `tools.jar` and the classes required for dynamic attach are available in the base JDK image.

**Comment by jbachorik** [comment]
There is improved TOOLS_JAR detection in the develop branch to correctly deal with pre-jigsaw as well as the current JDKs.
Can you give it a try using the build from the develop branch?
