### ISSUE TITLE
!ERROR java.lang.NullPointerException

### ISSUE THREAD

**Issue by scutlxp** [btraceio/btrace#409]
Hi, I get a NPE when I use `BTraceUtils.Sys.Memory.heapUsage()` or `BTraceUtils.Sys.Memory.nonHeapUsage()`. It appeared in the v2.0.0 version, and it works correctly in v1.3.11.3

![aaa](https://user-images.githubusercontent.com/30747378/77289632-4c4bd380-6d15-11ea-8797-1bd0be52489c.png)

**Comment by jbachorik** [comment]
Memory MBeans were initialized only if low-memory handlers were present in the script.
Fixed now in develop.
