### ISSUE TITLE
Why I BTrace script has't not result but 0

### ISSUE THREAD

**Issue by JMCuixy** [btraceio/btrace#412]
Hi, i am a newbie of Btrace.

I have written a script, as follows
```
import org.openjdk.btrace.core.BTraceUtils;
import org.openjdk.btrace.core.annotations.*;

@BTrace
public class Hello {

    @OnMethod(clazz = "org.jvm.demo.chapter4.btrace.BtraceCase",
            method = "add",
            location = @Location(Kind.RETURN)
    )
    public static void run(@Self Object self, int a, int b,
                           @Return int result,
                           @Duration long time
    ) {
        BTraceUtils.print("params, a = " + a + ",b=" + b);
        BTraceUtils.print("result, result = " + result);
        BTraceUtils.print("costs, time = " + time);
    }
}
```
but when i execute this script, has't nothing print but 0, as show
```
$ ./btrace.bat  8516 Hello.java
0
```
I spent a day to solve the problem，could you give me some help？

**Comment by jbachorik** [comment]
1. What is the `0` output ? It does not seem to correspond to anything in that trace script.
2. Can you run `btrace.bat -v ...` to get verbose debug and paste it here?

**Comment by JMCuixy** [comment]
> 1. `0`输出是什么？它似乎与该跟踪脚本中的任何内容都不对应。
> 2. 您可以运行`btrace.bat -v ...`获取详细的调试信息并将其粘贴到此处吗？

thanx for reply.  brace.bat -v  ... result as show
```
$ ./btrace.bat -v 1668 Hello.java
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
DEBUG: compiling Hello.java
DEBUG: compiled Hello.java
DEBUG: attaching to 1668
DEBUG: checking port availability: 2020
DEBUG: attached to 1668
DEBUG: loading D:\btace\libs\btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=D:\JAVA\jdk1.8.0_202\lib\tools.jar,probeDescPath
=.
0

```

**Comment by jbachorik** [comment]
This is a far shot but - is your `BtraceCase` class in `org.jvm.demo.chapter4.btrace` package?

Also, the traced application will print out debug info too - it is even more interesting than the debug from the `btrace` command line utility as it will show you which classes and methods were instrumented. If you could add it here as well that would be awesome.

**Comment by jbachorik** [comment]
I have recently experienced something similar when trying to attach to JVM running on JDK 13 from BTrace client running on JDK 8 (and vice versa). The problem is that the requirements for the attach api are very different - JDK 8 needs tools.jar while JDK 9+ has the necessary classes in the JDK image. And it is very difficult, nigh impossible to detect such mismatch and handle it in a meaningful way :(
