### ISSUE TITLE
Null pointer exception while trying to trace one of the spark method 

### ISSUE THREAD

**Issue by mjose007** [btraceio/btrace#414]
```
package com.manu.experiments;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.Kind;
import com.sun.btrace.annotations.Location;
import com.sun.btrace.annotations.OnMethod;

/**
 * @author Manu Jose
 * create on : 06/04/20
 */
@BTrace(unsafe=true)
public class BtraceScript {

    @OnMethod(clazz="org.apache.spark.sql.execution.streaming.ProgressReporter$", method="updateProgress",
            location=@Location(Kind.RETURN))
    public static void onQueryProgress(org.apache.spark.sql.streaming.StreamingQuery streamingQueryProgress) {
//        BTraceUtils.println("New file is being created");
//        System.out.println("\n\n\n\n\n\nThis method got the call\n\n\n\n\n");
    }
    @OnMethod(clazz="apache.spark.sql.streaming.ui.StreamingQueryStatusListener", method="onQueryProgress",
            location=@Location(Kind.RETURN))
    public static void onQueryProgress(org.apache.spark.sql.streaming.StreamingQueryListener.QueryProgressEvent streamingQueryProgress) {
//        BTraceUtils.println("New file is being created");
//        System.out.println("\n\n\n\n\n\nThis method got the call\n\n\n\n\n");
    }
}

```

this is my btrace script i am trying to trace one streaming application 

but when i run 

`./btrace  -cp /Users/manujose/experiments/target/experiments-1.0-SNAPSHOT-jar-with-dependencies.jar 84563 /Users/manujose/experiments/src/main/java/com/manu/experiments/BtraceScript.java`

i am getting below error , dont know why 
`Exception in thread "main" java.lang.NullPointerException
	at com.sun.btrace.client.Client.submit(Client.java:367)
	at com.sun.btrace.client.Main.main(Main.java:194)
Exception in thread "Thread-0" java.lang.IllegalStateException
	at com.sun.btrace.client.Client.send(Client.java:485)
	at com.sun.btrace.client.Client.sendExit(Client.java:419)
	at com.sun.btrace.client.Main$2.run(Main.java:228)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by jbachorik** [comment]
Can you please provide the BTrace version?
Also, the JVMs started by Apache Spark are ephemeral so I don't think that dynamic attach will work for them - they can die any time while you are trying to attach to them. The only reliable option is to start those JVMs with the BTrace agent and tracing script(s).

**Comment by jbachorik** [comment]
Any chance to provide more info?
