### ISSUE TITLE
Can BTrace sending the trace info to another host using socket communication?

### ISSUE THREAD

**Issue by TheodoreSKong** [btraceio/btrace#420]
Recently I'm using BTrace to monitor an application A on **host I**, can I send the trace information via socket to another app B on **host II** (the host is used to analyze the runtime data)? 
or can I modify which part of the source code to achieve this ?

**Comment by jbachorik** [comment]
You can utilize the trusted mode (`@BTrace(trusted = true)`) and then use sockets as you would in any other Java program.

You can also check StatsD integration (https://github.com/btraceio/btrace/blob/master/btrace-statsd/src/main/java/org/openjdk/btrace/statsd/Statsd.java) if all you need is transmitting metrics.

**Comment by TheodoreSKong** [comment]
is there any guide on this ? I haven't found the guide of the trusted mode in Wiki

> utilize the trusted mode (@BTrace(trusted = true)) and then use sockets as you would in any other Java program.

**Comment by TheodoreSKong** [comment]
Does this mean that I can implement a new btrace-client using sockets by modifying the existing one in source code under the trusted mode?

> is there any guide on this ? I haven't found the guide of the trusted mode in Wiki
> 
> > utilize the trusted mode (@btrace(trusted = true)) and then use sockets as you would in any other Java program.
