### ISSUE TITLE
Hi ,  if i  get the changes of variables a and b in the whole process using btrace?

### ISSUE THREAD

**Issue by xiao1i** [btraceio/btrace#427]
like this demo, if i can get the whole changes of a and b?
eg: firstly a = 2 , then a = 3 .

// a = 2 b = 3
    private int add(int a, int b) {
        a++; // a = 3;
        b--; // b = 2;
        a += b; // a = 5
        return a + b; // return 7
    }

**Comment by jbachorik** [comment]
Sorry, currently it is not possible.
