### ISSUE TITLE
Btrace output beyond Strings?

### ISSUE THREAD

**Issue by lollipopman** [btraceio/btrace#428]
I have created the following btrace script which dumps the string version of a
java.security.cert.X509Certificate object during an SSL handshake. I would love
to call the getEncoded() method on that object to get a DER encoded version of
the cert. Is that possible with btrace? Thanks, Jesse

```
import org.openjdk.btrace.core.annotations.BTrace;
import org.openjdk.btrace.core.annotations.OnMethod;
import org.openjdk.btrace.core.annotations.Location;
import org.openjdk.btrace.core.annotations.BTrace;
import org.openjdk.btrace.core.annotations.Kind;
import org.openjdk.btrace.core.annotations.Location;
import org.openjdk.btrace.core.annotations.OnMethod;
import org.openjdk.btrace.core.annotations.Return;

import java.lang.reflect.Field;
import static org.openjdk.btrace.core.BTraceUtils.*;
import javax.net.ssl.*;

@BTrace
public class ProbeSSLHandshake {
    private static Field certField = field("sun.security.ssl.SSLSessionImpl", "peerCerts");
    private static java.lang.Object[] peerCerts;
    @OnMethod(
        clazz = "javax.net.ssl.HandshakeCompletedEvent",
        method = "getSession",
        location = @Location(Kind.RETURN)
    )
    public static void methodReturn(@Return SSLSession session) {
        peerCerts = (java.lang.Object[])get(certField, session);
        printArray(peerCerts);
    }
}
```

**Comment by jbachorik** [comment]
Calling arbitrary methods is not allowed by default as it may mutate the application state (and even worse, long term storage).
However, you can run you script in trusted mode (with `@BTrace(trusted = true)`) where you can use basically anything available in Java.

**Comment by lollipopman** [comment]
thanks @jbachorik that is really helpful, is there anyway to vet a method to determine if it is safe to call?

**Comment by jbachorik** [comment]
Mostly manually :( You must be sure that it is not mutating any critical resources (DB etc.) and that it is mostly sideeffect-free (or you are running on a non-prod where the sideffects can be tolerated).

**Comment by lollipopman** [comment]
Awesome thanks @jbachorik, closing this issue as all my questions have been answered!
