### ISSUE TITLE
tools.jar  does not exist.

### ISSUE THREAD

**Issue by realyong** [btraceio/btrace#434]
when I run using:
 btrace -cp classes 19280 TraceTest.java

the program(19280) prints a warning: 
btrace WARNING: BTrace system classpath resource [C:\tools\Java\jdk1.8.0_202\jre/lib/tools.jar] does not exist.

@BTrace
public class TraceTest{

    @OnMethod(clazz="java.lang.Thread", method="start")

    public static void onThreadStart() {
        println("thread start!");

    }
}

when starts a thread in program(19280) ,no message:thread start! (2.0.2 can,but 2.0.3 can't)

**Comment by lingpeiyong** [comment]
because C:\tools\Java\jdk1.8.0_202\jre/lib/tools.jar really has tools.jar.
tools.jar usually in dir of jdk_home/lib/ , not in jre. so you can copy by manual
