### ISSUE TITLE
How to check the self method duration

### ISSUE THREAD

**Issue by mgazizova** [btraceio/btrace#448]
Hello!
I want to check the self method duration. 

For example

```
// full executed 2.5 sec
method1() {
  method2() { // full executed 2 sec }
}
```

The results what I need: 
method2() - 2 sec;  
method1() - 0.5 sec;

How can I do this?

**Comment by jbachorik** [comment]
You need to track both of those methods via `@OnMethod` probe definition and use a shared `@LTS` (local-thread storage) to accumulate the duration - eg. first add the negative `@Duration` value for `method2` on its return and then add the summary duration of `method1` upon its return. This should give you the 'cleansed' duration of `method1`.

**Comment by jbachorik** [comment]
Closing.
If you need more information, feel free to reopen.
