### ISSUE TITLE
jdk11 Class verification failed

### ISSUE THREAD

**Issue by zhenbianshu** [btraceio/btrace#473]
I'm using openjdk 11 on CentOS 6 docker container, jetty server, spring, btrace v2.2.0

```
openjdk 11 2018-09-25
OpenJDK Runtime Environment COMPANYjdk (build 11+28-201904040926)
OpenJDK 64-Bit Server VM COMPANYjdk (build 11+28-201904040926, mixed mode)
```

When I started btrace, I got a warning message and nothing expected output:
`[BTRACE WARN] Class verification failed: com.test.MyClass (null)`

When server responsed,  I got log in com.test.MyClass.test, but nothing in STD.

this is btrace debug message following:
```
DEBUG: assuming default port 2020
DEBUG: assuming default classpath '.'
btrace INFO: Attaching BTrace to PID: 474
DEBUG: compiling LogBtrace.java
DEBUG: compiled LogBtrace.java
DEBUG: Boot classpath: .
DEBUG: attaching to 474
DEBUG: checking port availability: 2020
DEBUG: attached to 474
DEBUG: loading /docker/opt/logs/btrace/libs/btrace-agent.jar
DEBUG: agent args: port=2020,statsd=,debug=true,bootClassPath=.,systemClassPath=/usr/local/jdk-11+28_1/lib/tools.jar,probeDescPath=.
DEBUG: loaded /docker/opt/logs/btrace/libs/btrace-agent.jar
DEBUG: registering shutdown hook
DEBUG: registering signal handler for SIGINT
DEBUG: submitting the BTrace program
DEBUG: opening socket to 2020
DEBUG: setting up client settings
DEBUG: sending instrument command: [debug=1]
DEBUG: entering into command loop
DEBUG: received org.openjdk.btrace.core.comm.RenameCommand@7e7be63f
DEBUG: received org.openjdk.btrace.core.comm.StatusCommand@614ca7df
DEBUG: received org.openjdk.btrace.core.comm.RetransformationStartNotification@66d3eec0
DEBUG: received org.openjdk.btrace.core.comm.MessageCommand@f5acb9d
[BTRACE WARN] Class verification failed: com.test.MyClass (null)
DEBUG: received org.openjdk.btrace.core.comm.StatusCommand@4fb3ee4e
btrace INFO: Successfully started BTrace probe: LogBtrace.java
DEBUG: received org.openjdk.btrace.core.comm.StatusCommand@5d7148e2
```

And this is my btrace script:
```
 @BTrace
public class LogBtrace {
     @OnMethod(clazz = "com.test.MyClass", method = "test")
     public static void m(@ProbeClassName String pcm, @ProbeMethodName String pmn) {
         println(pcm);
          println(pmn);
     }
}
```
I want to kown why Class Verification error and How can I solve this problem, Thank you!

**Comment by zhenbianshu** [comment]
Maybe classLoader? I tried arthas and arthas had this problem too, this problem solved when I set classLoader in arthas property.

**Comment by jbachorik** [comment]
The error comes from the built-in Java class verifier. Unfortunately, it is not very verbose about the actual verification error.

Can you try running BTrace with `-d /tmp/btrace_debug` argument (or other location where you can store the bytecode of the instrumented classes) and then attach the file `/tmp/btrace_debug/com/test/MyClass.class`? That should provide more insight about what was  incorrectly instrumented (if anything).

Out of curiosity - what is this `COMPANYjdk` version?

**Comment by zhenbianshu** [comment]
Hi, the enhanced class file link is: [MyClass.class](https://github.com/zhenbianshu/Javalab/blob/master/MyClass.class).
And COMPANYjdk is a customized version jdk, I think it may cause this problem at first, but I still found this problem when I tried public jdk version later.

**Comment by jbachorik** [comment]
The class file has a totally corrupted content. Is that class loader you mentioned doing custom bytecode modifications?

**Comment by zhenbianshu** [comment]
> The class file has a totally corrupted content. Is that class loader you mentioned doing custom bytecode modifications?

I‘m not sure because my app was started up with jetty runner and spring mvc. Maybe I should check it myself, thank you.

**Comment by jbachorik** [comment]
Have you been able to figure out why the class got corrupted?
I am going to close the issue now - if you have more information and want to proceed, please feel free to reopen.
