### ISSUE TITLE
git clone  not successful

### ISSUE THREAD

**Issue by tgl123** [btraceio/btrace#478]
$ git clone https://github.com/btraceio/btrace.git  btrace-develope
Cloning into 'btrace-develope'...
remote: Enumerating objects: 17430, done.
remote: Counting objects: 100% (1169/1169), done.
remote: Compressing objects: 100% (589/589), done.
remote: Total 17430 (delta 335), reused 1047 (delta 271), pack-reused 16261
Receiving objects: 100% (17430/17430), 16.26 MiB | 5.86 MiB/s, done.
Resolving deltas: 100% (9743/9743), done.
error: invalid path 'btrace-runtime/src/main/java/org/openjdk/btrace/runtime/aux/Auxilliary.java'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

error: invalid path 'btrace-runtime/src/main/java/org/openjdk/btrace/runtime/aux/Auxilliary.java'

**Comment by jbachorik** [comment]
Please, try again and/or check your system set up.
I have just verified that the cloning works as expected.

```
aroslav.bachorik@COMP-C02FJ0PSMD6V /tmp % git clone https://github.com/btraceio/btrace.git
Cloning into 'btrace'...
remote: Enumerating objects: 17430, done.
remote: Counting objects: 100% (1169/1169), done.
remote: Compressing objects: 100% (590/590), done.
remote: Total 17430 (delta 335), reused 1046 (delta 270), pack-reused 16261
Receiving objects: 100% (17430/17430), 16.26 MiB | 3.46 MiB/s, done.
Resolving deltas: 100% (9743/9743), done.
jaroslav.bachorik@COMP-C02FJ0PSMD6V /tmp %
```

**Comment by muzinian** [comment]
See [this ](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names):

> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

**Comment by jbachorik** [comment]
@muzinian Thanks. This explains that.
Sorry, haven't been running windows dev env for many, many years :(
