### ISSUE TITLE
btrace can't  run : show ""D:\Program Files\Java\jdk-11.0.11/jmods/" was unexpected at this time."

### ISSUE THREAD

**Issue by tgl123** [btraceio/btrace#479]
$ ./btrace.bat -h
"D:\Program Files\Java\jdk-11.0.11/jmods/" was unexpected at this time.

Administrator@FQ-202104130900 MINGW64 /d/phpstudy_pro/WWW/java/btrace-develope/bin (develop)
$ java --version
java 11.0.11 2021-04-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.11+9-LTS-194, mixed mode)

**Comment by jarek-przygodzki** [comment]
Looks like the `btrace.bat` from  #458 is incorrent.

**Comment by jarek-przygodzki** [comment]
`btrace.bat` must be run from _cmd.exe_, the Windows command interpreter.

**Comment by jbachorik** [comment]
Indeed. In MINGW the bash script (not *.bat) should be used.

**Comment by lingpeiyong** [comment]
btrace.bat has bug, use exists, but cmd.exe command use exist;
