### ISSUE TITLE
can not trace the constructor method use jdk8 in window10

### ISSUE THREAD

**Issue by lingpeiyong** [btraceio/btrace#483]
@OnMethod(clazz = "java.util.concurrent.ConcurrentHashMap", method = "<init>", location = @Location(Kind.ENTRY))
    public static void traceThrowable2(@Self Object self) {
        BTraceUtils.println("ConcurrentHashMap constructor ");
 }
Above code can not print anything when I new ConcurrentHashMap();
And I find OnThrow.java(your exception printing stack trace * of an exception) can not work too; I infer it is also because of this problem

**Comment by jbachorik** [comment]
Unfortunately, `ConcurrentHashMap` is one of 'sensitive classes' (https://github.com/btraceio/btrace/blob/215e16213384a375f8d75e69df70e3b51e08dbc1/btrace-instr/src/main/java/org/openjdk/btrace/instr/ClassFilter.java#L94) - meaning that allowing unchecked instrumentation may compromise the BTrace engine consistency as well as the traced application.

With the move to JDK 15 and later where BTrace can not use a neat trick of adding private static methods as the probe handlers and needs to define a hidden class in the private lookup of the instrumented class and then use method handles to invoke the probe methods. This requires a 'bootstrap' when the call site is linked - and this, in turn, will use a bunch of classes from eg `java.util` package. This would cause the bootstrap handler waiting for instrumentation and the instrumentation would wait for the bootstrap handler, effectively deadlocking the traced application if the instrumentation is the first user of such a class (the class is not loaded yet).

Omitting such sensitive classes from instrumentation is the easiest fix for now - unless I come up with some clever way to instrument such classes only after they had been accessed (or pre-touch them during startup - which will have adverse effect on the application startup time, though)

**Comment by lingpeiyong** [comment]
if you can not trace  sensitive classes, you can tip user you can not trace, for a good ui,if you do not tip,user will be baffle
如果你不能跟着这些敏感类,那最好能提示用户你不能跟踪这些类,这样ui体验会更好,不然使用的时候都莫名其妙的

**Comment by jbachorik** [comment]
Actually, when you enable BTrace debug output there is already a `skipping transform for BTrace class  ...` message for all classes skipped because of their sensitivity.
