### ISSUE TITLE
Getting Trace of Classes in External Libraries

### ISSUE THREAD

**Issue by EhsanMashhadi** [btraceio/btrace#484]
Hi,

Is it possible to get the trace of classes that are parts of libraries/dependencies we use?

I have some test classes which contain assert statements (`org.junit.Assert`). I want to trace both classes under tests and assert statements after running tests. 

Would you please help me with this?

**Comment by jbachorik** [comment]
Of course. The only limit is what JVM can see - so, as long as the library classes are loaded (eg. by using them) you can create and install a probe there.
The syntax and process it the same as for your application classes.

Cheers!

**Comment by EhsanMashhadi** [comment]
I could not see any logs related to the Junit. I need the assert methods, but they do not appear in the output. Would you please help me?

Assuming that my classes are in `pack` package, and my test classes are in `testpack` method:

Trace Script:
```
    @OnMethod(clazz = "/(testpack.*)|(pack.*)|(org.junit.*)/")
    public static void onMethod(@ProbeMethodName String pmn, AnyType[] args) {
        String output = pmn;
        print(output);
    }
```

Commands:

1) `btracec [script file]`
2) `btrace [script_file] -cp [directory] org.junit.runner.JUnitCore TestClass`

It runs the tests, and generates the logs, but I only can see the method name in my classes in `pack` package, and there is no log regarding the Junit methods like `assertEquals‍‍‍‍‍‍‍‍‍‍‍‍‍‍` which are used in my TestClasses.

**Comment by jbachorik** [comment]
> btrace [script_file] -cp [directory] org.junit.runner.JUnitCore TestClass

Did you mean `btracer [script_file] -cp [directory] org.junit.runner.JUnitCore TestClass` - the BTrace application runner?

Can you run it like `btracer -v -d /tmp/btrace [script_file] ...`  to enable debug logs and also to capture the instrumented classes in `/tmp/btrace` location? When you have those, please, attach them here so I can inspect them. 

Thanks for the patience!
