### ISSUE TITLE
BTrace probe's output is not being redirected for the first connection. 

### ISSUE THREAD

**Issue by ksiczek** [btraceio/btrace#498]
I have a rather simple btrace script and I connect to JBoss 7 JVM 8 on Fedora 34. I would like to redirect the output to a file using `-o` switch but it does not seem to work for the first time I connect to JVM (probes are printed to the standard output) and I have to do Ctrl+C and connect again - then it works. Is this something you guys know about? Is the `-o` reliable and is there any difference than standard redirect `>`?

The other thing I noticed is that if I use `-o` and exit the btrace then connect again without `-o` it still redirects to the file. I might not comprehend how btrace works in terms of restarting/reconnecting but having the `-o` working for the very first time is important to me.

**Comment by jbachorik** [comment]
Hi @ksiczek, thanks for reporting this.
I will try looking into this in the near future.
