### ISSUE TITLE
the btrace.bat file in the last release (btrace-v2.2.0-bin.zip) is wrong

### ISSUE THREAD

**Issue by Junior233** [btraceio/btrace#507]
the btrace.bat file in the last release (btrace-v2.2.0-bin.zip) is wrong. like this

![image](https://user-images.githubusercontent.com/67447332/142752555-f4ce8fd9-1566-497a-9e6f-a1d20ed550c7.png)

but the source code is :
![image](https://user-images.githubusercontent.com/67447332/142752590-65086f05-c0de-4bc7-96ed-d8c2c1753a19.png)

[btrace-v2.2.0-bin.zip](https://github.com/btraceio/btrace/files/7575847/btrace-v2.2.0-bin.zip)

**Comment by jbachorik** [comment]
The source is for the trunk where this bug was fixed - #491
