### ISSUE TITLE
Requirements on Sampling

### ISSUE THREAD

**Issue by TheodoreSKong** [btraceio/btrace#508]
Dear Developers,

I need to monitoring the applications using sampling rules like "instrument at the method exit 100 times every 1000 invocations ", can this be achieved via Btrace tools?

**Comment by jbachorik** [comment]
Yes, you can achieve this with the built-in sampling - see [this blogpos](https://btraceio.github.io/btrace/2015/02/sampled-profiling)

**Comment by TheodoreSKong** [comment]
> Yes, you can achieve this with the built-in sampling - see [this blogpost](https://btraceio.github.io/btrace/2015/02/sampled-profiling)

sorry, I see there are two ways to sample, one is adaptive, the other is constant. but I want to sampling the app with two parameters, D for durations (number of functions that are instrumented) and d for interval (number of functions between two monitoring jobs). no matter then whether a function is monitored for many times. if this can be achieveed in the const mode? I have no idea.

**Comment by TheodoreSKong** [comment]
[sampling.pdf](https://github.com/btraceio/btrace/files/7717739/sampling.pdf)
 the sampling process is like this figure shows.

**Comment by jbachorik** [comment]
The `Const` sampler can help you with your requirement to `instrument at the method exit 100 times every 1000 invocations`.
It is using [Inverse Transform Sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling) behind the scenes to pick each N-th execution of the probe, where `N` is given as the annotation parameter.
Eg. `@Sampled(kind = Sampled.Sampler.Const, mean = 20)` will pick each 20th execution of the probe in average - the interval between two subsequent sampled probes will vary randomly but the average interval will still be `N`.

I hope this answers your question.

**Comment by TheodoreSKong** [comment]
I’m sorry, but I’m still confused.
There are only one parameter, the mean of sampling interval, how can we control the duration? 
`instrument at the method exit 100 times every 1000 invocations ` the mean seems to achieve the `1000`, how can we achieve the `100`… I want to use the sampling in all method instruments, like instrumenting the name of 100 continuous method name and time stamps , then sleep for 1000, then continue instrumenting another continuous 100 method exit.

hope I have clearly introduced the problem 😅

**Comment by TheodoreSKong** [comment]
Or we should set `mean = (1000+100)/100=11` If we want to achieve the example?

**Comment by jbachorik** [comment]
Ah, now I understand. 
Unfortunately, what you describe is not supported. The built in sampler provides random sampling - whereas your requirements are heavily biasing the sample to the start of each 1000 of invocations.
You would need to do it yourself with invocation/sample counters and conditional skipping of the probe.

**Comment by TheodoreSKong** [comment]
Thanks,
Can you show me the location in the source code to achieve this counter?
I’m a freshman to Java and this is my first time to deal with such a large project 🧐

**Comment by jbachorik** [comment]
This would be something you would need to do in the BTrace probe you write.
There are examples of those probes in https://github.com/btraceio/btrace/tree/develop/btrace-dist/src/main/resources/samples

**Comment by jbachorik** [comment]
Closing the issue. If you want to discuss possible approaches to this, please use https://github.com/btraceio/btrace/discussions
