### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by mianqiangsheng** [btraceio/btrace#525]
![image](https://user-images.githubusercontent.com/66811677/155484425-25bd40d4-0971-4f00-bc79-91e9d8339394.png)
this error occurred on windows 
![image](https://user-images.githubusercontent.com/66811677/155484722-5e7f18ba-aa38-4af8-be86-2139ce653f78.png)
this error occurred on linux 
my application sdk is jdk1.8.0_212 and btrace version is btrace-v2.2.1-bin.

**Comment by jbachorik** [comment]
For the Windows example, what `java BTrace` is actually doing? According to the error message it seems like you have the BTrace agent classes loaded by several different classloaders (eg. having BTrace agent classes on the application classpath).

Regarding the linux issue - can you run BTrace in verbose mode `./btrace -v <PID> ...` and attach the whole log here?

Thanks!
