### ISSUE TITLE
btrace 2.2.1 can not work in openjdk11 and openjdk17,but openjdk8 is well

### ISSUE THREAD

**Issue by baymax55** [btraceio/btrace#527]
btrace version :btrace2.2.1

os version: windows 11

java version: `openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)`
execute command:`btrace --help`
errMSg:`Error: Could not find or load main class "-XX:+IgnoreUnrecognizedVMOptions
Caused by: java.lang.ClassNotFoundException: "-XX:+IgnoreUnrecognizedVMOptions`

**Comment by chusifeng** [comment]
Hi！ I use 2.2.1 is ok，JDK11，I extract the command from the startup script in the bin directory， like this：

`java -XX:+IgnoreUnrecognizedVMOptions -XX:+AllowRedefinitionToAddDeleteMethods --add-exports jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED -cp %BTRACE_HOME%/libs/btrace-client.jar org.openjdk.btrace.client.Main -v 16712 BTraceTest.java`

Please replace with your own PID and script  **16712 BTraceTest.java**

**Comment by jbachorik** [comment]
Hi @baymax55  - this is most probably an issue with Windows 11 command line.
Unfortunately, I don't have Windows 11 available so I will need some external help in getting the script fixed. I expect the root cause would be space escaping but, as I said, I have no access to Windows 11 to test it.

**Comment by wylswz** [comment]
Here's problematic command

```
"C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot/bin/java" """-XX:+IgnoreUnrecognizedVMOptions" --add-exports jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED"" -cp "C:\Program Files\btrace\bin\../libs/btrace-client.jar;C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot/lib/tools.jar" org.openjdk.btrace.client.Main
```

I removed the quotation mark on stmt `set JAVA_ARGS=-XX:+IgnoreUnrecognizedVMOptions` then it worked, [here](https://github.com/wylswz/btrace/commit/97ef6ac2bdced0dfdc6992f09fceccdc0c037f0d)'s the fix.

**Comment by jbachorik** [comment]
Hi @wylswz , would you mind opening a PR for this so the fix can be properly attributed?
If you are not covered by your employee regarding OCA, you would need to sign it first, though. (https://oca.opensource.oracle.com/)

**Comment by wylswz** [comment]
Of cause, my agreement is being reviewed, will do that later
