### ISSUE TITLE
REG questions

### ISSUE THREAD

**Issue by TheodoreSKong** [btraceio/btrace#538]
I have used the reg following:
`"/org\\.apache\\.cassandra\\..*/"`
to  match the methods under "org.apache.cassandra.xxx.xxx"
but can't match the methods `org.apache.cassandra.concurrent.xxx`
but reg `/org.apache.cassandra..*/` can do this well
I don't know how this problems happen?

**Comment by jbachorik** [comment]
The unescaped `.` in the regex will match any single character - so it will match also the `.` literal.

As for why the first regex is not matching - you can run BTrace with `-v` flag in verbose mode where all matching attempts will be logged so you can check whether the classes are actually being evaluated or not.
Other than that it is not really clear - the regex within `/...../` is compiled to the Java regex `Pattern` and used like that. So, whatever the java regex engine would match based on the pattern should also be matched in BTrace.

**Comment by TheodoreSKong** [comment]
i meet some warns like following, which may related with problems,

btrace INFO: Attaching BTrace to PID: 6739 
[BTRACE WARN] Class verification failed: org.apache.cassandra.utils.obs.OpenBitSet (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.utils.MurmurHash (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.utils.EstimatedHistogram (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.utils.btree.BTreeSet$BTreeRange (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.utils.BackgroundActivityMonitor (null)
R:      HintsWriteExecutor:1    org.apache.cassandra.utils.concurrent.OpOrder$Barrier.<init>    -Duration6079

**Comment by jbachorik** [comment]
Hm, this does not look too good. What version of BTrace are you using?

**Comment by TheodoreSKong** [comment]
The newest release 2.2.2
and I find that this happened when I use the all method scripts and at that time the Cassandra app will throw NoClassDefFoundError and cannot be connected with the CQL client it seems an performance issue? Can performance issue will cause NoClassDefFoundError? I’m really fresh to this aera…

**Comment by TheodoreSKong** [comment]
I’m not sure if it is a problem in the Cassandra or btrace.. can all methods monitoring cause errors in the monitored apps? I have used an elder version last year with the all methods monitoring, I guess it works at that time 😅 but I’m not sure 🫣

**Comment by jbachorik** [comment]
Well, instrumenting all methods may take time. If there are any liveness checks they may fail.
But it should not cause `NoClassDefFoundError` - if you happen to hit it again, could you attach the log or the exception trace here?

**Comment by TheodoreSKong** [comment]
error log from btrace:

> [BTRACE WARN] Class verification failed: org.apache.cassandra.hints.HintsWriteExecutor$PartiallyFlushBufferPoolTask$$Lambda$195/1157505821 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.hints.HintsDispatchTrigger$$Lambda$192/945116782 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.hints.HintsDispatchTrigger$$Lambda$188/1627175418 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.hints.HintsWriteExecutor$$Lambda$187/96676134 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.service.NativeTransportService$$Lambda$185/1877159738 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.batchlog.BatchlogManager$$Lambda$174/134710032 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.hints.HintsService$$Lambda$173/1158442790 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.lifecycle.View$$Lambda$117/1439273114 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.partitions.PartitionUpdate$$Lambda$67/571147428 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.partitions.PartitionUpdate$$Lambda$65/2084549386 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.rows.BTreeRow$$Lambda$62/370753406 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.partitions.PurgeFunction$$Lambda$57/1173236118 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.commitlog.CommitLogSegmentManager$1$$Lambda$51/2017458666 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.lifecycle.LogAwareFileLister$$Lambda$48/1412601264 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.lifecycle.LogAwareFileLister$$Lambda$44/634297796 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.Directories$SSTableLister$$Lambda$36/1409160703 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.ClusteringComparator$$Lambda$24/1839337592 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.ClusteringComparator$$Lambda$23/686989583 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.ClusteringComparator$$Lambda$22/1207608476 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.ClusteringComparator$$Lambda$21/842179210 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.config.ColumnDefinition$$Lambda$17/1740846921 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.config.ColumnDefinition$$Lambda$16/2014461570 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.db.marshal.AbstractType$$Lambda$11/904861801 (null)
[BTRACE WARN] Class verification failed: org.apache.cassandra.io.sstable.IndexSummaryManager (null)


and error log from Cassandra:

> btrace WARNING: Unknown slot type: -2
ERROR 02:11:46 Exception in thread Thread[BatchlogTasks:1,5,main]
java.lang.NoClassDefFoundError: org/apache/cassandra/db/lifecycle/View$$Lambda$86
	at org.apache.cassandra.db.lifecycle.View$$Lambda$86/467196683.get$Lambda(Unknown Source) ~[na:na]
	at org.apache.cassandra.db.lifecycle.View.selectLive(View.java:239) ~[main/:na]
	at org.apache.cassandra.db.PartitionRangeReadCommand.queryStorage(PartitionRangeReadCommand.java:178) ~[main/:na]
	at org.apache.cassandra.db.ReadCommand.executeLocally(ReadCommand.java:394) ~[main/:na]
	at org.apache.cassandra.db.ReadCommand.executeInternal(ReadCommand.java:424) ~[main/:na]
	at org.apache.cassandra.service.pager.AbstractQueryPager.fetchPageInternal(AbstractQueryPager.java:77) ~[main/:na]
	at org.apache.cassandra.service.pager.PartitionRangeQueryPager.fetchPageInternal(PartitionRangeQueryPager.java:39) ~[main/:na]
	at org.apache.cassandra.cql3.UntypedResultSet$FromPager$1.computeNext(UntypedResultSet.java:190) ~[main/:na]
	at org.apache.cassandra.cql3.UntypedResultSet$FromPager$1.computeNext(UntypedResultSet.java:179) ~[main/:na]
	at org.apache.cassandra.utils.AbstractIterator.hasNext(AbstractIterator.java:47) ~[main/:na]
	at org.apache.cassandra.batchlog.BatchlogManager.processBatchlogEntries(BatchlogManager.java:231) ~[main/:na]
	at org.apache.cassandra.batchlog.BatchlogManager.replayFailedBatches(BatchlogManager.java:207) ~[main/:na]
	at org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable.run(DebuggableScheduledThreadPoolExecutor.java:118) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_333]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_333]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_333]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_333]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_333]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_333]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_333]
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.db.lifecycle.View$$Lambda$86
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_333]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_333]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_333]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_333]
	... 20 common frames omitted
btrace WARNING: Unknown slot type: -2

**Comment by TheodoreSKong** [comment]
> Hm, this does not look too good. What version of BTrace are you using?

I have tried the previous version 1.3.11.3, which rare hit this problem, only 1 or 2 this error after a long time running of All methods scripts.

**Comment by jbachorik** [comment]
Hi @TheodoreSKong , 

I tried something like 
```java
import org.openjdk.btrace.core.annotations.BTrace;
import org.openjdk.btrace.core.annotations.OnMethod;
import org.openjdk.btrace.core.annotations.ProbeClassName;
import org.openjdk.btrace.core.annotations.ProbeMethodName;
import org.openjdk.btrace.core.annotations.Self;

import static org.openjdk.btrace.core.BTraceUtils.*;

/**
 * This script traces method entry into every method of
 * every class in javax.swing package! Think before using
 * this script -- this will slow down your app significantly!!
 */
@BTrace
public class AllMethods1 {
    @OnMethod(
            clazz = "/org\\.apache\\.cassandra\\..*/",
            method = "/.*/"
    )
    public static void m(@Self Object o, @ProbeClassName String probeClass, @ProbeMethodName String probeMethod) {
        println("this = " + o);
        print("entered " + probeClass);
        println("." + probeMethod);
    }
}
```

on Apache Cassandra 4.0.4, JDK 11.0.15 and BTrace trunk build (`BTrace v.2.3.0-SNAPSHOT (2bc335a565f906f82964cc3ec6df6bb8941f5b91`) and things work as expected without any class verification errors or Cassandra stopping working.

Can you please verify with the trunk build? IMO, the problem was fixed by some fixes related to stack map frames which went to trunk after release 2.2.2.

**Comment by TheodoreSKong** [comment]
thanks for your continuously supporting, I will try it later.
