### ISSUE TITLE
how to avoid IllegalAccessExceptions

### ISSUE THREAD

**Issue by kushal-ti** [btraceio/btrace#555]
I'm running BTrace in trusted mode on a spingboot application, and when i run the application, i get many instances of 
```java
java.lang.IllegalAccessException: class org.openjdk.btrace.instr.ClassInfo cannot access a member of class java.lang.ClassLoader (in module java.base) with modifiers "static"
```
followed by a lengthy stack trace all the way to the main method of the application. 
For what it's worth, i've made sure the the regex for class name and method names used by BTrace onEntry and onReturn methods is excluding my main method, but the error still persists. Apart from the main, i don't have any other static method in the program, so i don't know what the root of this problem really is.
Does it have something to do with springboot class loaders ?

It doesn't affect the working of the program but it is noisy and i'd like to know if there's a way to silence it

**Comment by jbachorik** [comment]
Duplicated by #558
