### ISSUE TITLE
Unsupported class file major version 29281

### ISSUE THREAD

**Issue by joachimhs** [btraceio/btrace#575]
Hello, 

I am getting the following when I am trying to start my Java Application via the command line. I have built the app on JDK 16, and I am starting it on JDK 16. Using the Brace 2.2.2 download from GitHub. I am running this in an Apple Silicon Mac. 

What version of Java do I need to use?

**Comment by joachimhs** [comment]
Hm. It seems that when I run BTrace with -javaagent, and use the scriptdir command, it picks up any file in that directory. Not only .class files. So the file .DS_Store (that gets automatically generated on Macs for each folder), is picked up and attempted to load into the Java application.

**Comment by jbachorik** [comment]
This is very strange - there is definitely no version 29281 of the java class format.

Can you provide the exact steps to reproduce, please?

**Comment by joachimhs** [comment]
Hello, 

Looking at this, it seems that BTrace attempts to pick up any file in the scriptdir directory, so when it tries to pick up this ".DS_Store" file, it throws that exception. 

<img width="710" alt="Skjermbilde 2022-09-10 kl  07 57 56" src="https://user-images.githubusercontent.com/453373/189471287-a686d669-458f-4ee8-ad5d-2564d1b97289.png">

I think there ought to be a filter that filters out anything not ending with .class when loading script files from a directory.

**Comment by joachimhs** [comment]
Created PR: https://github.com/btraceio/btrace/pull/580
