### ISSUE TITLE
Javaagent args for output directory seems wrong

### ISSUE THREAD

**Issue by joachimhs** [btraceio/btrace#578]
Hello, 

The Javaagent parameter for SCRIPT_OUTPUT_DIR seems wrong. It is defined in Args.java: 

- public static final String SCRIPT_OUTPUT_DIR = "scriptdir";

Back in the BTrace 1.x days I believe there where a "scriptdir" that pointed to the directory where the .class script files where located, and a "scriptOutputDir" which pointed to the directory where all of the output would be redirected to. 

So I think this could be changed to: 

- add a public static final String SCRIPT_DIR = "scriptdir"
- change the SCRIPT_OUTPUT_DIR to be public static final String SCRIPT_OUTPUT_DIR = "scriptOutputDir".

**Comment by jbachorik** [comment]
Ah 🤦  ....

This got messed up during refactoring - the script dir value seem to have been referred to by 'scriptdir' in one place and 'scriptDir' in another place and during refactoring I somehow made it even worse and mixed it up with `scriptOutputDir`.

Please, go ahead and open a PR for this.

**Comment by joachimhs** [comment]
Created https://github.com/btraceio/btrace/pull/579
