### ISSUE TITLE
Adding XStream to the dependencies error

### ISSUE THREAD

**Issue by amirdeljouyi** [btraceio/btrace#592]
As part of instrumentation, I wanted to serialize an object by using ```XStream``` and the ```JettisonMappedXmlDriver``` driver, and I've added dependencies to the build.gradle files of ```btrace-runtime```, ```btrace-core```, and ```btrace-agent```.
 It seems that ```com/thoughtworks/xstream/XStream``` is not found, and I receive a ```java.lang.NoClassDefFoundError``` error.

In ```BTraceRuntimeImplBase```, I implement serializing with XStream as follows:
```
@Override
  public final void writeJSON(Object obj, String fileName) {
    try {
      Path p = FileSystems.getDefault().getPath(resolveFileName(fileName));
      try (BufferedWriter bw = Files.newBufferedWriter(p, StandardCharsets.UTF_8)) {
        if (obj == null || bw == null) {
          throw new NullPointerException();
        }
        XStream xstream = new XStream(new JettisonMappedXmlDriver());
        bw.write(xstream.toXML(obj));
        bw.flush();
      }
    } catch (RuntimeException re) {
      throw re;
    } catch (Exception exp) {
      throw new RuntimeException(exp);
    }
  }
```
If you could help me with this, I'd really appreciate 🙏

**Comment by amirdeljouyi** [comment]
I've solved it by adding the dependencies into relocate and include in the build.gradle file of the btrace-dist project.

**Comment by jbachorik** [comment]
I am glad you found a solution. 
Next time, please, use the 'Discussions' section - this is technically not a product issue.
