### ISSUE TITLE
Windows batch scripts do not work properly

### ISSUE THREAD

**Issue by magicwerk** [btraceio/btrace#630]
btracer.bat
- script does not work as there is a superfluous space in the path in "if not exist "%BTRACE_HOME%\libs \btrace-agent.jar" goto noBTraceHome"
- if a option like "--stdout" is passed, script does not work
- if JAVA_ARGS is not set, the script does not work

btracec.bat
- if JAVA_ARGS is not set, the script does not work

**Comment by jbachorik** [comment]
Hi @magicwerk , 
Thanks for reporting this!

Unfortunately, I don't have access to a Windows machine. If anyone  with a Windows machine would be up to providing a working patch, it would be awesome.
